"""Cross-lane Protocols (docs/spec net.md §6, modes.md §7, armory.md §5). Lanes implement or
consume these; never import another lane's module internals."""
from __future__ import annotations

from typing import Any, Callable, Protocol

from .types import (ArmoryRecord, Envelope, Event, FrameBundle, GameConfig, Player, RosterEntry,
                    ScanRow, ScoreRow, Team, Weapon)


class Hello(dict):
    """hello body: node_id, node_type, app_ver, gun?{name, tail, fw?}, seq_next"""


class WelcomeNode(dict):
    """welcome.node: player, team, roster, config, frames, start?, match_id?, score?"""


class NetServer(Protocol):
    async def start(self, host: str, port: int, ws_path: str = "/ws") -> None: ...   # real server is async; FakeNet may be sync
    def join_info(self) -> dict: ...                       # {url, session_id, qr}
    def hydrate(self, cb: Callable[[Hello], WelcomeNode | None]) -> None: ...
    def on_node(self, cb: Callable[[dict], None]) -> None: ...
    def on_event(self, cb: Callable[[str, Event, int], None]) -> None: ...        # (node_id, ev, t_recv) — single facts
    def on_batch(self, cb: Callable[[str, list, int], None]) -> None: ...          # (node_id, events, t_recv) — a flushed event_batch (A5.7)
    def on_status(self, cb: Callable[[str, dict, int], None]) -> None: ...
    def on_node_message(self, cb: Callable[[str, str, dict, int], None]) -> None: ...  # (node_id, kind, body, t_recv)
    def on_stale(self, cb: Callable[[str, int], None]) -> None: ...
    def on_return(self, cb: Callable[[str], None]) -> None: ...
    def push(self, node_id: str, kind: str, body: dict) -> None: ...
    def broadcast(self, kind: str, body: dict) -> None: ...


class Compiler(Protocol):
    def compile(self, config: GameConfig, player: Player, teams: list[Team]) -> FrameBundle: ...
    def tutorial_frames(self, weapon: Weapon, environment: str) -> list[str]: ...
    def cues(self, voice: str) -> dict[str, str]: ...
    def validate(self, config: GameConfig, roster: list[Player], opts: dict | None = None) -> dict: ...
    def weapon_catalog(self) -> list[Weapon]: ...
    def award_medals(self, rows: list[ScoreRow], kills: list[dict]) -> dict[str, list[str]]: ...


class Armory(Protocol):
    def list(self) -> list[ArmoryRecord]: ...
    async def scan(self, duration_s: int = 6) -> list[ScanRow]: ...
    def bind_player(self, gun_id: str, player_id: str) -> None: ...
