// GENERATED by mcp/tools/gen_contract.py from mcp/brx_mcp/mc/types.py + envelope.py (+ protocol.PANIC_SEQUENCE) -- do not edit; run python3 mcp/tools/gen_contract.py
#pragma once
#include <cstddef>
#include <cstdint>
#include <cstring>

namespace brx::contract {

struct StrPair { const char* key; const char* value; };

// A row of an int table, by its key (the `<NAME>_KEYS` array); `fallback` for a key the row lacks.
inline int32_t lookup(const int32_t* row, const char* const* keys, size_t n, const char* key, int32_t fallback) {
  for (size_t i = 0; i < n; ++i) if (key && std::strcmp(keys[i], key) == 0) return row[i];
  return fallback;
}

// ---- constants (types.py §9 + envelope.py's module-level constants) ----
constexpr int32_t ASSIST_WINDOW_MS = 4000;
constexpr int32_t MULTI_KILL_MS = 4000;
constexpr int32_t FEEDBACK_MAX_AGE_MS = 3000;
constexpr int32_t STATUS_HEARTBEAT_MS = 2000;
constexpr int32_t STALE_AFTER_MS = 8000;
// F52: the A16.3 gun readout's timings, shipped in `gun.readout`. One owner here, so the generator emits them
// to the phone (contract.gen.js) and poolgauge / presentation / the stage import them: no literal copies left
// to disagree after a bench retune. Their meanings are documented at poolgauge.py's readout section.
constexpr int32_t READOUT_LEAD_MS = 180;
constexpr int32_t READOUT_BLINK_GAP_MS = 80;
constexpr int32_t READOUT_STEP_MS = 120;
constexpr int32_t READOUT_BLINK_MS = 400;
constexpr int32_t READOUT_MIN_GAP_MS = 400;
constexpr int32_t READOUT_HOLD_S = 4;
// The `sync_age_ms` a LIVE row carries when MC has never heard its node in THIS process (no node bound,
// or MC restarted mid-match and the phone has not spoken since). It is a sentinel, not an age: the
// console must print "not heard", never "11d13h ago" (visual QA H3, 2026-09-23).
constexpr int32_t NEVER_SEEN_MS = 1000000000;
// A24/M2: how far apart two cap-reaching kills may be and still count as the SAME moment. contracts.md
// §7 gives no single number -- it says phone clocks "drift <<1 s over a match" after a lobby re-sync, so
// 1 s is the width of the band inside which MC cannot tell which of two kills landed first. Two players
// reaching the frag cap inside it are reported as a TIE rather than decided by MC's arrival order.
constexpr int32_t CLOCK_TIE_MS = 1000;
// F119: the smallest shot count an accuracy number is worth believing. Hits arrive per EVENT and shots
// only on the ~2 s status heartbeat, so a row with a handful of shots swings wildly between samples and
// can read over 100 %. `honors()` already refused SHARPSHOOTER below this; `ScoreRow.acc_provisional`
// now says the same thing about the live number instead of leaving the UI to guess.
constexpr int32_t ACC_MIN_SHOTS = 10;
// Past this, a node has not merely gone quiet — it is gone (phone asleep, app closed, gear packed
// away). Everything else the board would say about it (gun link lost, clock unsynced, wrong wi-fi,
// screen off) is a CONSEQUENCE of that, and listing them as separate faults turns a switched-off
// tagger into a wall of red alarms (field 2026-09-02).
constexpr int32_t OFFLINE_AFTER_MS = 600000;
constexpr int32_t SYNC_FRESH_MS = 10000;
// A32: how long `status.preflight.gun_linked` must stay TRUE CONTINUOUSLY before the link itself is
// accepted as proof that a headset is attached. A gun with NO headset accepts a BLE link and answers a
// `$PING`, then drops it within ~6 s (manual/hardware.md, manual/dev.md); switching a linked headset off
// makes the gun send `$DISCONNECT,*` and drop the same way. So a link that SURVIVES is the headset --
// 10 s is the ~6 s drop plus margin for a slow phone and the ~2 s status heartbeat. Shorter and a
// headless gun's dying link would read as proven; much longer and the board sits amber for no reason.
constexpr int32_t HEADSET_LINK_PROOF_MS = 10000;
constexpr int32_t LATE_ARM_GRACE_MS = 8000;
constexpr int32_t CONFIG_TTL_MS = 1800000;
// wire ids 1..63; 0 reserved (tutorial / unknown shooter)
constexpr int32_t MAX_PLAYERS = 63;
// F366 (Tony 2026-09-25): a gamertag is at most MAX_TAG_LEN characters after trim + upper-case; MC refuses a
// longer one (never a silent cut). Past SOFT_TAG_LEN the console warns that the phone HUD may shorten it.
constexpr int32_t MAX_TAG_LEN = 16;
constexpr int32_t SOFT_TAG_LEN = 12;
constexpr int32_t DEATH_LATCH_MS = 2000;
// A34: a phone still LIVE in a match MC has retired is told `control{end}` from its status heartbeat; this
// is how long MC waits before telling the SAME phone about the SAME match again (the first end normally lands).
constexpr int32_t STALE_LIVE_RETELL_MS = 10000;
// A36: how long after a life begins MC waits before believing the pool a gun reports. The `$SPAWN`
// and the head's `$PSET` are two BLE writes and a relay apart, and the ~2 s status heartbeat can be
// sampled between them -- so the first frame or two of a life legitimately carries the previous
// pool. Past this the gun has had a whole heartbeat to settle and a pool that still disagrees with
// the pushed `$PSET` is the gun running a different game.
constexpr int32_t POOL_CHECK_SETTLE_MS = 2000;
constexpr int32_t RESYNC_PROBE_S = 10;
// Tony 2026-09-25: "default countdown 30s. 120s is generally too long." The ONE default for a START
// with no runway_s (api.py start/reschedule, state.py Session.start, the console's runway.ts and the
// generated contract all read this one constant). An explicit runway a host passes is unaffected.
constexpr int32_t DEFAULT_RUNWAY_S = 30;
constexpr int32_t PROTOCOL_V = 1;
// The venue volume (field-corrected 2026-08-30: 80 = on-gun L3 indoors, 90 = L4 outdoors) and the
// bounds of the host's per-game knob, `GameConfig.volume`. The floor is on-gun L1: 30 is inaudible
// for game audio, so the knob cannot choose silence.
constexpr int32_t VENUE_VOLUME_INDOOR = 80;
constexpr int32_t VENUE_VOLUME_OUTDOOR = 90;
constexpr int32_t GAME_VOLUME_MIN = 60;
constexpr int32_t GAME_VOLUME_MAX = 100;
// pieces.json (`pieces.PieceStore`)
constexpr int32_t PIECES_STORE_V = 1;
// favourites.json (`favourites.FavouriteStore`)
constexpr int32_t FAVOURITES_STORE_V = 1;
// the session snapshot (`state.Session` persist)
constexpr int32_t SESSION_STORE_V = 1;
constexpr int32_t TIMED_PROTECT_S_DEFAULT = 0;
constexpr int32_t WEAPON_DELAY_MS_DEFAULT = 500;
constexpr int32_t STATION_PROTECT_S_DEFAULT = 2;
// A58: the station tamper lock (`station_config.lock_s`). The LOAD value covers a lobby wait of up to
// STATION_LOCK_LOBBY_S plus the match, because a muster station hears nothing after the lobby push.
constexpr int32_t STATION_LOCK_MAX_S = 7200;
constexpr int32_t STATION_LOCK_LOBBY_S = 1800;
constexpr int32_t STATION_LOCK_MARGIN_S = 120;
// a boot instant (t_recv - uptime_s) that moves further than this is a new boot
constexpr int32_t STATION_REBOOT_SLACK_MS = 5000;
// timed: the trigger goes live at least this long after protection ends
constexpr int32_t TRIGGER_AFTER_PROTECT_MS = 500;
// a death this soon after a timed respawn raises the down-screen warning
constexpr int32_t SPAWN_KILL_WINDOW_MS = 10000;
// A6 (architecture review #4, 2026-10-04): the ONE table of station presence defaults, per platform and kind. A station
// whose `station_config.threshold` is 0 measures (and advertises in byte 14) its platform's value here. Generated into
// contract.gen.ts/.js and hardware/m5sticks3/contract.gen.h, so the phone (beacon.js), the console (Items.tsx), the
// Stick (station_range.h) and MC (`stations.wire_threshold`) all read this one copy.
// phone respawn -70: Tony 2026-09-24, walked at 3-5 m. phone powerup -55: S58, about 30 cm, a placeholder until
// bench 4.11. phone control -75: F383, Tony 2026-09-27, until the outdoor walk. Any other phone kind -74.
// sticks3 respawn -57: Tony 2026-09-24 ("the stick actually works better"). sticks3 powerup -45: F434, Tony
// 2026-09-28, about 30 cm. sticks3 control -75: UNPROVEN, Sitting B 2026-09-25, a 5-7 m target. Any other Stick
// kind takes the Stick respawn value.
constexpr const char* STATION_DEFAULT_THRESHOLD_DBM_KEYS[] = {"respawn", "powerup", "extraction", "bomb", "control"};
constexpr size_t STATION_DEFAULT_THRESHOLD_DBM_COUNT = 5;
constexpr int32_t STATION_DEFAULT_THRESHOLD_DBM_PHONE[] = {-70, -55, -74, -74, -75};
constexpr int32_t STATION_DEFAULT_THRESHOLD_DBM_STICKS3[] = {-57, -45, -57, -57, -75};
constexpr int32_t STATION_DEFAULT_THRESHOLD_DBM_PHONE_RESPAWN = -70;
constexpr int32_t STATION_DEFAULT_THRESHOLD_DBM_PHONE_POWERUP = -55;
constexpr int32_t STATION_DEFAULT_THRESHOLD_DBM_PHONE_EXTRACTION = -74;
constexpr int32_t STATION_DEFAULT_THRESHOLD_DBM_PHONE_BOMB = -74;
constexpr int32_t STATION_DEFAULT_THRESHOLD_DBM_PHONE_CONTROL = -75;
constexpr int32_t STATION_DEFAULT_THRESHOLD_DBM_STICKS3_RESPAWN = -57;
constexpr int32_t STATION_DEFAULT_THRESHOLD_DBM_STICKS3_POWERUP = -45;
constexpr int32_t STATION_DEFAULT_THRESHOLD_DBM_STICKS3_EXTRACTION = -57;
constexpr int32_t STATION_DEFAULT_THRESHOLD_DBM_STICKS3_BOMB = -57;
constexpr int32_t STATION_DEFAULT_THRESHOLD_DBM_STICKS3_CONTROL = -75;
// A defaulted Stick HILL advertises -57 in byte 14 (the value the Stick advertised before the hill had its own default:
// Tony's Stick respawn walk, 2026-09-24), while the Stick itself measures players at
// STATION_DEFAULT_THRESHOLD_DBM["sticks3"]["control"]. Its own constant, so retuning the Stick respawn does not move it.
constexpr int32_t STICK_HILL_ADVERT_THRESHOLD_DBM = -57;
// F345: a phone station's defaults, sent explicitly instead of 0 to a phone app older than PHONE_THRESHOLD_ZERO_APP
// (which clamps 0 to -30 dBm). Read from the table above.
constexpr int32_t PHONE_RESPAWN_THRESHOLD_DBM = -70;
constexpr int32_t PHONE_STATION_THRESHOLD_DBM = -74;
constexpr int32_t PHONE_POWERUP_THRESHOLD_DBM = -55;
constexpr int32_t PHONE_CONTROL_THRESHOLD_DBM = -75;
// advert byte 9 "any team" (`TEAM_ANY` in beacon.js); a control point starts neutral
constexpr int32_t STATION_TEAM_ANY = 255;
// A7/D11 (architecture review #4): the presence and hill numbers the phone station (app/src/beacon.js, utility.js,
// control.js) and the Stick (hardware/m5sticks3/presence.h) must share. spec/utility.md §5d has the rules.
// the entry dwell a utility station applies (utility.js DEFAULTS.dwell)
constexpr int32_t PRESENCE_DWELL_MS = 800;
// F440: Tony 2026-10-02, the exit level is this far below the threshold
constexpr int32_t PRESENCE_EXIT_BAND_DB = 3;
// F440: leaving needs this long below the exit level (body shadowing, 2-5 s)
constexpr int32_t PRESENCE_EXIT_GRACE_MS = 4000;
// a player not heard for this long is gone
constexpr int32_t PRESENCE_EXPIRY_MS = 4000;
// a credible sighting counts for this long (= the silence expiry)
constexpr int32_t PRESENCE_SIGHT_MS = 4000;
// a sighting is the median of the adverts heard in this window
constexpr int32_t PRESENCE_SIGHT_WINDOW_MS = 2000;
// P-L1: the most adverts the sighting window keeps
constexpr int32_t PRESENCE_SIGHT_RECENT_MAX = 64;
// the RSSI EMA weight
constexpr double PRESENCE_ALPHA = 0.35;
// the raw-sample median before the EMA
constexpr int32_t PRESENCE_MEDIAN_SAMPLES = 3;
// F344
constexpr int32_t REVIVE_MARGIN_DB = 10;
// a station's presence tick
constexpr int32_t STATION_TICK_MS = 250;
// control.js DEFAULT_CAPTURE_S
constexpr int32_t HILL_CAPTURE_S = 10;
// control.js DEFAULT_NET_CAP: the most a net difference counts for
constexpr int32_t HILL_NET_CAP = 3;
// control.js: the longest step one tick may advance the hill
constexpr int32_t HILL_MAX_STEP_MS = 1000;
// F82: control.js REFUSED_TID
constexpr int32_t HILL_REFUSED_TID = 2;
// A11 (architecture review #4): the config bounds MC enforces (`Session._merge_config`) and the console steppers stop at.
// time_limit_s 1..this
constexpr int32_t TIME_LIMIT_MAX_S = 7200;
// respawn.delay_s 0..this
constexpr int32_t RESPAWN_DELAY_MAX_S = 600;
// mode_params.hold_target_s 1..this
constexpr int32_t HOLD_TARGET_MAX_S = 7200;
// S-powerup-overrides (2026-09-28, Tony): ARMORY's per-station powerup override ranges (powerups.py checks them).
// Tony's own picks, not a protocol limit. 240, not 300: the StickS3 carries spawn_every_s in one byte.
constexpr int32_t POWERUP_CHARGES_MIN = 1;
constexpr int32_t POWERUP_CHARGES_MAX = 4;
constexpr int32_t POWERUP_AMOUNT_MIN = 25;
constexpr int32_t POWERUP_AMOUNT_MAX = 150;
constexpr int32_t POWERUP_AMOUNT_STEP = 25;
constexpr int32_t POWERUP_SPAWN_EVERY_MIN = 30;
constexpr int32_t POWERUP_SPAWN_EVERY_MAX = 240;
constexpr int32_t POWERUP_SPAWN_EVERY_STEP = 30;
// A9 (architecture review #4): the $SIR function classes compile.py builds by and the phone's engine reads.
// registers a $HIR, moves no pool
constexpr int32_t SIR_NO_POOL_FNS[] = {8, 23, 24, 25, 26, 27, 28, 31, 32, 34, 35};
constexpr size_t SIR_NO_POOL_FNS_COUNT = 11;
// heals/armour/shields: a "damage" weapon here HELPS the target
constexpr int32_t SIR_GRANT_FNS[] = {9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22};
constexpr size_t SIR_GRANT_FNS_COUNT = 14;
// A67: an edit age at or above this is "the station restarted since, the time is lost". A Stick has no clock
// across a reboot, so it reports a LARGE age; MC's value then wins on the next `station_config`.
constexpr int32_t STATION_EDIT_AGE_UNKNOWN_MS = 86400000;
// A67 polish: MC dates an adopted station edit `t_recv - age`, later than the true edit by the uplink latency. While a
// field's source is "station", MC adds this to the age it sends, so the station's own edit is always the younger one
// and it keeps src "station" through every re-send (A58's START/END locks).
constexpr int32_t ADOPT_SLACK_MS = 10000;
// A1/A12 (architecture review #4): the team vocabulary by $TID (index 0-3), generated for the phone, the console and
// the Stick. F423: tid 3 is GREEN on the wire (`$TID,3`) but PAINTS and is NAMED purple everywhere a person sees it.
// The hex values are the --team-* CSS tokens (app/www/index.html, utility.html) and the Stick's screen; the inks are the
// dark text on them. MC's own console and roster (state.py TEAM_DEFS, webapp/mc/src/tokens.ts TEAM) keep their own
// palette: red is #ff5252 there, not #f43f5e; blue, yellow and purple match. A change to one is not a change to the other.
constexpr const char* TEAM_KEYS[] = {"red", "blue", "yellow", "purple"};
constexpr size_t TEAM_KEYS_COUNT = 4;
constexpr const char* TEAM_NAMES[] = {"RED", "BLUE", "YELLOW", "PURPLE"};
constexpr size_t TEAM_NAMES_COUNT = 4;
constexpr const char* TEAM_ABBRS[] = {"RED", "BLU", "YEL", "PUR"};
constexpr size_t TEAM_ABBRS_COUNT = 4;
constexpr const char* TEAM_COLOUR_HEX[] = {"#f43f5e", "#3a86ff", "#ffd23f", "#bf4ce6"};
constexpr size_t TEAM_COLOUR_HEX_COUNT = 4;
constexpr const char* TEAM_INK_HEX[] = {"#1a0404", "#04121e", "#1a1400", "#140a1c"};
constexpr size_t TEAM_INK_HEX_COUNT = 4;
// A12: the weapon role labels a person sees (the HUD's weapon card, the console's class tag).
constexpr StrPair ROLE_LABELS[] = {{"assault", "ASSAULT"}, {"cqb", "CLOSE RANGE"}, {"marksman", "SNIPER"}, {"support", "SUPPORT"}, {"power", "HEAVY"}, {"melee", "MELEE"}, {"sidearm", "SIDEARM"}};
constexpr size_t ROLE_LABELS_COUNT = 7;
// contracts.md §5 "Size cap" (the retired net.md §8)
constexpr int32_t MAX_ENVELOPE_BYTES = 65536;
// log_data chunk cap (fits under the envelope cap)
constexpr int32_t MAX_LOG_CHUNK_BYTES = 49152;
// Plausibility window for `t` (Unix ms): reject obvious garbage (seconds instead of ms, negative,
// far future). A node with a wrong clock still lands inside this window; MC keeps t_recv anyway.
// 2017-07
constexpr int64_t T_MIN_MS = 1500000000000LL;
// 2096
constexpr int64_t T_MAX_MS = 4000000000000LL;
constexpr const char* PANIC_SEQUENCE[] = {"$CLEAR,*", "$SP,99,*"};
constexpr size_t PANIC_SEQUENCE_COUNT = 2;

// ---- kind vocabularies (STATION_KINDS in source order: advert byte 8 = index + 1) ----
constexpr const char* MC_KINDS[] = {"ack", "alert", "apply", "assign", "config", "control", "feedback", "join", "loadout_ack", "pull_log", "result", "score", "start", "station_config", "station_update", "time_res", "tutorial", "welcome"};
constexpr size_t MC_KINDS_COUNT = 18;
constexpr const char* NODE_KINDS[] = {"ack_config", "bind", "event", "event_batch", "hello", "loadout_browse", "loadout_request", "log_data", "log_offer", "ready", "station_action", "status", "time_req"};
constexpr size_t NODE_KINDS_COUNT = 13;
constexpr const char* CONTROL_CMDS[] = {"abort_start", "end", "panic", "recall", "release_utility", "relink", "respawn", "resync"};
constexpr size_t CONTROL_CMDS_COUNT = 8;
constexpr const char* PERSISTED_EVENT_TYPES[] = {"death", "hit_taken", "operator_result", "pickup", "possession", "respawn", "team_change"};
constexpr size_t PERSISTED_EVENT_TYPES_COUNT = 7;
constexpr const char* STATION_KINDS[] = {"respawn", "powerup", "extraction", "bomb", "control"};
constexpr size_t STATION_KINDS_COUNT = 5;
constexpr const char* NODE_DENIED_COMMANDS[] = {"ASKSN", "BOOM", "BURN", "CDFU", "CLEARDEVICE", "DDFU", "DEV", "DPLAY", "DTYPE", "DUTY", "FACTORY", "FTST", "GPAIR", "GPAIRX", "HEADDFU", "INQ", "IRT", "MUZ", "PAIR", "PIN", "RESET", "SETUP", "SITE", "SOL", "TSTRNAME", "VIBTOGGLE", "ZOFF", "ZOM", "ZOMBIEKEYACTIVE", "ZON", "ZTOG"};
constexpr size_t NODE_DENIED_COMMANDS_COUNT = 31;
constexpr const char* STATION_SOURCE_IDS[] = {"grenade", "ir_station", "phone"};
constexpr size_t STATION_SOURCE_IDS_COUNT = 3;

}  // namespace brx::contract
