#!/usr/bin/env python3
"""Generate the two client copies of the node<->MC wire contract from its one Python source.

    python3 mcp/tools/gen_contract.py            # rewrite both files
    python3 mcp/tools/gen_contract.py --check    # exit 1 if either is stale (what the test does)

Source of truth: `mcp/brx_mcp/mc/types.py` (constants, Literal aliases, TypedDicts, the kind
vocabularies) and `mcp/brx_mcp/mc/envelope.py` (`REQUIRED`/`EVENT_REQUIRED`/`ACCEPT_MIN`, plus its
own module-level UPPER_CASE constants -- the two size caps and the `t` sanity bounds). `docs/spec/
contracts.md` stays the human spec of record and generates nothing; this script generates the two
machine copies the UI and the phone app used to hand-keep:

  webapp/mc/src/api/contract.gen.ts   MC console (Vite/TS) -- constants, `type` aliases, every
                                      TypedDict as an `interface`, kind vocabularies as
                                      `[...] as const` arrays + their `typeof ...[number]` type,
                                      and the REQUIRED/EVENT_REQUIRED/ACCEPT_MIN tables.
  app/src/transport/contract.gen.js  phone app (esbuild) + node tests/tools -- the same constants
                                      and tables, kind vocabularies as `Set`s (matched to the exact
                                      literal form `test_contract_kinds.py`'s `_js_set()` regex and
                                      `test_mc_envelope_kinds.py` expect, so those tests can be
                                      pointed at this file later without touching their parsers).

Whole-file generation, not marker splicing: nothing hand-written lives in either output. Stdlib
only -- no dependency on the MC package having any of its own dependencies installed (it has none;
this script imports `brx_mcp.mc.types` / `.envelope` directly, which are pure).

2026-09-12 (contract-DRY phase 1, per docs scratch/contract-dry-spec.md). Modeled on
`gen_ui_catalog.py` (same `render()` / `main()` shape) and `test_ui_catalog_generated.py` (same
in-memory-render-vs-disk test pattern).
"""
from __future__ import annotations

import ast
import io
import pathlib
import re
import sys
import tokenize
import types as _pytypes
import typing
from dataclasses import dataclass, field
from typing import Any, Literal, get_args, get_origin, get_type_hints

_UNION_ORIGINS = {typing.Union, getattr(_pytypes, "UnionType", object())}

REPO = pathlib.Path(__file__).resolve().parents[2]
TYPES_PY = REPO / "mcp" / "brx_mcp" / "mc" / "types.py"
ENVELOPE_PY = REPO / "mcp" / "brx_mcp" / "mc" / "envelope.py"
TS_OUT = REPO / "webapp" / "mc" / "src" / "api" / "contract.gen.ts"
JS_OUT = REPO / "app" / "src" / "transport" / "contract.gen.js"

HEADER = ("GENERATED by mcp/tools/gen_contract.py from mcp/brx_mcp/mc/types.py + envelope.py "
          "-- do not edit; run python3 mcp/tools/gen_contract.py")

# Compatibility-statement constants, not wire fields -- the app has its own version source
# (app/package.json) and `types.parse_app_ver`/`app_tier` already read these two by name.
_CONST_DENY = {"APP_MAJOR", "APP_MINOR"}

_UPPER_NAME = re.compile(r"^[A-Z][A-Z0-9_]*$")

# A section-divider comment (types.py's "# ---- §9 constants ... ----" style) is a heading for a
# whole block of code, never one symbol's own preface/continuation -- it must never become part of
# any generated JSDoc. Matched on the comment text with its leading `#` (and any following
# whitespace) stripped.
_DIVIDER_RE = re.compile(r"^\s*-{3,}.*-{3,}\s*$")


# --------------------------------------------------------------------------- comment extraction #
#
# A field's/constant's JSDoc is assembled from three kinds of comment-only or trailing-comment
# source lines (spec contract-dry-spec.md §2.3):
#   preface     -- the run of comment-only lines directly ABOVE the statement that are not already
#                  claimed as another field's trailing/continuation comment.
#   own         -- a comment on the statement's own (last physical) line.
#   continuation-- comment-only lines directly BELOW whose text after `#` starts with 8+ spaces
#                  (types.py's style for a wrapped trailing comment).
# `consumed` is a set of line numbers shared across the whole file so a continuation claimed by
# one field cannot also become the next field's preface.

def _comment_maps(source: str) -> tuple[dict[int, str], dict[int, str]]:
    """(comment_only, trailing): line number -> the comment text with its leading `#` stripped.

    `comment_only`: the line's only real token is a COMMENT. `trailing`: the line has a COMMENT
    token alongside real code tokens. Built from `tokenize`, never by splitting a line on `#` by
    hand (a `#` can sit inside a string literal).
    """
    by_line: dict[int, list[tuple[int, str]]] = {}
    for tok in tokenize.generate_tokens(io.StringIO(source).readline):
        ttype, tstring, start, _end, _line = tok
        if ttype in (tokenize.NEWLINE, tokenize.NL, tokenize.INDENT, tokenize.DEDENT,
                     tokenize.ENDMARKER, tokenize.ENCODING):
            continue
        by_line.setdefault(start[0], []).append((ttype, tstring))
    comment_only: dict[int, str] = {}
    trailing: dict[int, str] = {}
    for lineno, toks in by_line.items():
        comments = [s for t, s in toks if t == tokenize.COMMENT]
        others = [s for t, s in toks if t != tokenize.COMMENT]
        if not comments:
            continue
        text = comments[0][1:]  # strip the leading '#' only, keep the space(s) after it
        if others:
            trailing[lineno] = text
        else:
            comment_only[lineno] = text
    return comment_only, trailing


def _statement_comment(node: ast.AST, comment_only: dict[int, str], trailing: dict[int, str],
                        consumed: set[int]) -> list[str] | None:
    """The assembled comment lines for one `ast` statement (a field's `AnnAssign` or a module-level
    `Assign`), in reading order: preface, own trailing, continuation. Marks every line it uses.

    A comment-only run directly below belongs to THIS field (continuation) only when the line
    itself is indented 8+ spaces after the `#` (types.py's style for wrapping a trailing comment,
    e.g. GameConfig.mode_params) -- checked per line, and unconditionally: a field's own same-line
    comment does NOT relax this, so a comment-only run with less indent is always the PREFACE of
    the NEXT symbol, never this one's continuation (contract-dry-spec.md review finding #1).

    A section-divider line (`_DIVIDER_RE`) is never included in either run: it is consumed (so
    nothing else can claim it) but stops the scan in that direction, since it marks the boundary of
    a whole section rather than describing the symbol on either side of it.
    """
    lineno = node.lineno
    end_lineno = getattr(node, "end_lineno", None) or lineno

    preface: list[str] = []
    ln = lineno - 1
    while ln in comment_only and ln not in consumed:
        text = comment_only[ln]
        consumed.add(ln)
        if _DIVIDER_RE.match(text):
            break
        preface.append(text)
        ln -= 1
    preface.reverse()

    own = trailing.get(end_lineno)
    if own is not None:
        consumed.add(end_lineno)

    continuation: list[str] = []
    ln = end_lineno + 1
    while ln in comment_only and ln not in consumed and comment_only[ln].startswith(" " * 8):
        text = comment_only[ln]
        consumed.add(ln)
        if _DIVIDER_RE.match(text):
            break
        continuation.append(text)
        ln += 1

    lines = preface + ([own] if own is not None else []) + continuation
    return [ln.strip() for ln in lines] if lines else None


def _jsdoc(lines: list[str] | None, indent: str = "") -> str | None:
    if not lines:
        return None
    lines = [ln.replace("*/", "*\\/") for ln in lines]
    if len(lines) == 1:
        return f"{indent}/** {lines[0]} */"

    def cont(ln: str) -> str:
        return f"{indent} *{'  ' + ln if ln else ''}"

    out = [f"{indent}/** {lines[0]}"]
    out.extend(cont(ln) for ln in lines[1:-1])
    last = lines[-1]
    out.append(f"{indent} *  {last} */" if last else f"{indent} */")
    return "\n".join(out)


def _docstring_jsdoc(doc: str | None, indent: str = "") -> str | None:
    if not doc:
        return None
    lines = [ln.strip() for ln in doc.strip("\n").split("\n")]
    while lines and not lines[-1]:
        lines.pop()
    return _jsdoc(lines, indent)


# ------------------------------------------------------------------------------- type mapping #

class UnmappedType(TypeError):
    pass


def _literal_args(tp: Any) -> tuple[Any, ...] | None:
    return get_args(tp) if get_origin(tp) is Literal else None


def _map_type(tp: Any, ctx: str, literal_alias_by_args: dict[tuple[Any, ...], str],
              typeddict_names: set[str]) -> str:
    if tp is type(None):
        return "null"
    if tp is str:
        return "string"
    if tp is bool:
        return "boolean"
    if tp is int or tp is float:
        return "number"
    if tp is Any:
        return "unknown"

    lit_args = _literal_args(tp)
    if lit_args is not None:
        alias = literal_alias_by_args.get(lit_args)
        if alias:
            return alias
        if not all(isinstance(a, str) for a in lit_args):
            raise UnmappedType(f"non-string Literal member(s) for {ctx}: {lit_args!r}")
        return " | ".join(f"'{a}'" for a in lit_args)

    origin = get_origin(tp)
    if origin in _UNION_ORIGINS:
        args = get_args(tp)
        mapped = [_map_type(a, ctx, literal_alias_by_args, typeddict_names) for a in args]
        deduped = list(dict.fromkeys(mapped))   # int|float both -> 'number'; keep first-seen order
        return " | ".join(deduped)

    if tp is list:
        return "unknown[]"
    if origin is list:
        args = get_args(tp)
        inner = _map_type(args[0], ctx, literal_alias_by_args, typeddict_names) if args else "unknown"
        return f"{inner}[]"

    if tp is dict:
        return "Record<string, unknown>"
    if origin is dict:
        args = get_args(tp)
        if len(args) == 2:
            return f"Record<string, {_map_type(args[1], ctx, literal_alias_by_args, typeddict_names)}>"
        return "Record<string, unknown>"

    if origin is tuple or tp is tuple:
        raise UnmappedType(f"tuple types are not supported on the wire -- {ctx}: {tp!r}")

    if typing.is_typeddict(tp):
        return tp.__name__
    if isinstance(tp, type) and tp.__name__ in typeddict_names:
        return tp.__name__

    raise UnmappedType(f"cannot map type for {ctx}: {tp!r}")


def _field_type_and_optional(hint: Any, ctx: str, literal_alias_by_args: dict[tuple[Any, ...], str],
                              typeddict_names: set[str], total: bool) -> tuple[str, bool]:
    NotRequired = typing.NotRequired
    Required = typing.Required
    origin = get_origin(hint)
    if origin is NotRequired:
        inner = get_args(hint)[0]
        return _map_type(inner, ctx, literal_alias_by_args, typeddict_names), True
    if origin is Required:
        inner = get_args(hint)[0]
        return _map_type(inner, ctx, literal_alias_by_args, typeddict_names), False
    return _map_type(hint, ctx, literal_alias_by_args, typeddict_names), not total


# ----------------------------------------------------------------------------------- discovery #

def _module_ast(path: pathlib.Path) -> tuple[str, ast.Module]:
    source = path.read_text(encoding="utf-8")
    return source, ast.parse(source, filename=str(path))


def _toplevel_assign_nodes(tree: ast.Module) -> dict[str, ast.AST]:
    """name -> the module-level `Name = ...` `ast.Assign` node that defines it (first one, in source
    order). Shared by every discovery function below that needs a symbol's own node to read its
    comments -- constants, Literal aliases, and kind-vocabulary sets/tuples alike."""
    nodes_by_name: dict[str, ast.AST] = {}
    for node in tree.body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            nodes_by_name.setdefault(node.targets[0].id, node)
    return nodes_by_name


def _literal_aliases(mod, tree: ast.Module) -> list[tuple[str, tuple[Any, ...], ast.AST | None]]:
    """Module-level `Name = Literal[...]` aliases, in module (source) order, with the `ast` node of
    the assignment (or None if it cannot be found) so its preface comment can become the alias's
    JSDoc (contract-dry-spec.md review finding #4)."""
    nodes_by_name = _toplevel_assign_nodes(tree)
    out = []
    for name, value in vars(mod).items():
        if get_origin(value) is Literal:
            out.append((name, get_args(value), nodes_by_name.get(name)))
    return out


def _typeddict_classes(mod, tree: ast.Module) -> list[tuple[ast.ClassDef, type]]:
    """`(ast node, runtime class)` for every TypedDict in `mod`, in source order."""
    out = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            cls = getattr(mod, node.name, None)
            if cls is not None and typing.is_typeddict(cls):
                out.append((node, cls))
    return out


def _module_constants(mod, tree: ast.Module) -> list[tuple[str, Any, ast.AST]]:
    """`(name, value, ast node)` for every module-level UPPER_CASE int/float/str constant, minus
    the deny-list, in module (source) order."""
    nodes_by_name = _toplevel_assign_nodes(tree)
    out = []
    for name, value in vars(mod).items():
        if name in _CONST_DENY or not _UPPER_NAME.match(name):
            continue
        if isinstance(value, bool) or not isinstance(value, (int, float, str)):
            continue
        node = nodes_by_name.get(name)
        if node is None:
            continue
        out.append((name, value, node))
    return out


# ---------------------------------------------------------------------------- envelope.py tables #

def _envelope_tables(env_mod) -> tuple[dict[str, tuple[str, ...]], dict[str, tuple[str, ...]],
                                        dict[str, tuple[str, ...]]]:
    """(REQUIRED, EVENT_REQUIRED, ACCEPT_MIN). Reads the private working names first so this keeps
    working before the contracts.md §3 rename (`_REQUIRED` -> `REQUIRED` etc, phase 2); falls back
    to the public names. `ACCEPT_MIN` does not exist yet at all -- defaults to `{}`."""
    required = getattr(env_mod, "_REQUIRED", None)
    if required is None:
        required = getattr(env_mod, "REQUIRED", None)
    if required is None:
        raise RuntimeError("envelope.py has neither _REQUIRED nor REQUIRED")
    event_required = getattr(env_mod, "_EVENT_REQUIRED", None)
    if event_required is None:
        event_required = getattr(env_mod, "EVENT_REQUIRED", None)
    if event_required is None:
        raise RuntimeError("envelope.py has neither _EVENT_REQUIRED nor EVENT_REQUIRED")
    accept_min = getattr(env_mod, "ACCEPT_MIN", {})
    return required, event_required, accept_min


class ContractInvariantError(ValueError):
    """ACCEPT_MIN violates one of its own two rules -- the generator refuses to publish a lie."""


def _validate_accept_min(accept_min: dict[str, tuple[str, ...]], mc_kinds: set[str],
                          required: dict[str, tuple[str, ...]]) -> None:
    """Two invariants ACCEPT_MIN (contract-dry-spec.md §3) must hold, checked at generation time so a
    typo in envelope.py fails the build loudly instead of shipping a receiver check that can never
    fire (an unknown kind) or that promises more than the sender is ever required to send:

      - every ACCEPT_MIN key names a real MC->node kind (`MC_KINDS`)
      - ACCEPT_MIN[kind] is a SUBSET of REQUIRED[kind] -- a receiver cannot safely require a field
        the sender's own REQUIRED table does not guarantee it sent.
    """
    for kind, fields in accept_min.items():
        if kind not in mc_kinds:
            raise ContractInvariantError(
                f"ACCEPT_MIN has kind {kind!r} which is not in MC_KINDS -- this receiver check can never fire")
        extra = set(fields) - set(required.get(kind, ()))
        if extra:
            raise ContractInvariantError(
                f"ACCEPT_MIN[{kind!r}] requires {sorted(extra)}, which REQUIRED[{kind!r}] does not "
                f"promise the sender ever sends")


# --------------------------------------------------------------------------------- rendering: TS #

def _ts_str_array(items: list[str]) -> str:
    return "[" + ", ".join(f"'{s}'" for s in items) + "]"


def _ts_table(name: str, table: dict[str, tuple[str, ...]]) -> str:
    if not table:
        return f"export const {name}: Record<string, readonly string[]> = {{}};"
    lines = [f"export const {name}: Record<string, readonly string[]> = {{"]
    for kind, fields in table.items():
        lines.append(f"  {kind}: {_ts_str_array(list(fields))},")
    lines.append("};")
    return "\n".join(lines)


def _render_ts(model: "_Model") -> str:
    out: list[str] = [f"// {HEADER}", ""]

    out.append("// ---- constants (types.py §9 + envelope.py's module-level constants) ----")
    for name, value, doc in model.constants:
        jd = _jsdoc(doc)
        if jd:
            out.append(jd)
        out.append(f"export const {name} = {_ts_lit(value)};")
    out.append("")

    out.append("// ---- Literal aliases ----")
    for name, args in model.literal_aliases:
        jd = model.literal_alias_docs.get(name)
        if jd:
            out.append(jd)
        union = " | ".join("'" + a + "'" for a in args)
        out.append(f"export type {name} = {union};")
    out.append("")

    out.append("// ---- kind vocabularies ----")
    alias_names = {name for name, _args in model.literal_aliases}
    for const_name, type_name, items in model.kind_sets:
        jd = model.kind_set_docs.get(const_name)
        if jd:
            out.append(jd)
        out.append(f"export const {const_name} = {_ts_str_array(items)} as const;")
        if type_name in alias_names:
            # `type_name` already exists as a `Literal` alias above (e.g. STATION_KINDS reusing
            # `StationKind` once types.py declares it) -- one name, one declaration. Re-emitting
            # `export type X = typeof CONST[number];` here would be a duplicate identifier (TS2300).
            continue
        out.append(f"export type {type_name} = typeof {const_name}[number];")
    out.append(f"export const STATION_SOURCE_IDS = {_ts_str_array(model.station_source_ids)} as const;")
    out.append("export type StationSourceId = typeof STATION_SOURCE_IDS[number];")
    out.append("")

    out.append("// ---- shapes (mcp/brx_mcp/mc/types.py TypedDicts) ----")
    for iface in model.interfaces:
        if iface.doc:
            out.append(iface.doc)
        out.append(f"export interface {iface.name} {{")
        for f in iface.fields:
            if f.doc:
                out.append(f.doc)   # already indented two spaces by _jsdoc(doc_lines, "  ")
            opt = "?" if f.optional else ""
            out.append(f"  {f.name}{opt}: {f.ts_type};")
        out.append("}")
        out.append("")

    out.append("// ---- required-field tables (mcp/brx_mcp/mc/envelope.py) ----")
    out.append(_ts_table("REQUIRED", model.required))
    out.append(_ts_table("EVENT_REQUIRED", model.event_required))
    out.append(_ts_table("ACCEPT_MIN", model.accept_min))
    out.append("")

    return "\n".join(out).rstrip("\n") + "\n"


def _ts_lit(value: Any) -> str:
    if isinstance(value, str):
        return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"
    return repr(value)


# --------------------------------------------------------------------------------- rendering: JS #

def _js_set_block(name: str, items: list[str]) -> str:
    lines = [f"export const {name} = new Set(["]
    for item in items:
        lines.append(f"  '{item}',")
    lines.append("]);")
    return "\n".join(lines)


def _js_table(name: str, table: dict[str, tuple[str, ...]]) -> str:
    if not table:
        return f"export const {name} = {{}};"
    lines = [f"export const {name} = {{"]
    for kind, fields in table.items():
        arr = "[" + ", ".join(f"'{s}'" for s in fields) + "]"
        lines.append(f"  {kind}: {arr},")
    lines.append("};")
    return "\n".join(lines)


def _js_lit(value: Any) -> str:
    if isinstance(value, str):
        return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"
    return repr(value)


def _render_js(model: "_Model") -> str:
    out: list[str] = [f"// {HEADER}", ""]

    # Same JSDoc as _render_ts for constants and kind sets -- the phone app loses nothing a
    # console reader gets (A33: the two files are one generation). Literal aliases/interfaces have
    # no JS equivalent (JS has no `type`/`interface`), so those two doc sources don't apply here.
    out.append("// ---- constants (types.py §9 + envelope.py's module-level constants) ----")
    for name, value, doc in model.constants:
        jd = _jsdoc(doc)
        if jd:
            out.append(jd)
        out.append(f"export const {name} = {_js_lit(value)};")
    out.append("")

    out.append("// ---- kind vocabularies ----")
    for const_name, _type_name, items in model.kind_sets:
        jd = model.kind_set_docs.get(const_name)
        if jd:
            out.append(jd)
        out.append(_js_set_block(const_name, items))
    out.append(_js_set_block("STATION_SOURCE_IDS", model.station_source_ids))
    out.append("")

    out.append("// ---- required-field tables (mcp/brx_mcp/mc/envelope.py) ----")
    out.append(_js_table("REQUIRED", model.required))
    out.append(_js_table("EVENT_REQUIRED", model.event_required))
    out.append(_js_table("ACCEPT_MIN", model.accept_min))
    out.append("")

    return "\n".join(out).rstrip("\n") + "\n"


# --------------------------------------------------------------------------------------- model #

class _Field(typing.NamedTuple):
    name: str
    ts_type: str
    optional: bool
    doc: str | None


class _Interface(typing.NamedTuple):
    name: str
    doc: str | None
    fields: list[_Field]


@dataclass(frozen=True)
class _Model:
    constants: list[tuple[str, Any, list[str] | None]]
    literal_aliases: list[tuple[str, tuple[Any, ...]]]
    kind_sets: list[tuple[str, str, list[str]]]   # (const_name, type_name, sorted items)
    station_source_ids: list[str]
    interfaces: list[_Interface]
    required: dict[str, tuple[str, ...]]
    event_required: dict[str, tuple[str, ...]]
    accept_min: dict[str, tuple[str, ...]]
    literal_alias_docs: dict[str, str | None] = field(default_factory=dict)   # name -> rendered JSDoc (or None)
    kind_set_docs: dict[str, str | None] = field(default_factory=dict)        # name -> rendered JSDoc (or None); see _build_model


def _build_model() -> _Model:
    sys.path.insert(0, str(REPO / "mcp"))
    from brx_mcp.mc import envelope as E
    from brx_mcp.mc import types as T

    types_src, types_tree = _module_ast(TYPES_PY)
    env_src, env_tree = _module_ast(ENVELOPE_PY)
    types_comment_only, types_trailing = _comment_maps(types_src)
    env_comment_only, env_trailing = _comment_maps(env_src)
    types_consumed: set[int] = set()
    env_consumed: set[int] = set()

    literal_aliases_raw = _literal_aliases(T, types_tree)
    literal_aliases = [(name, args) for name, args, _node in literal_aliases_raw]
    literal_alias_by_args = {args: name for name, args in literal_aliases}
    literal_alias_docs: dict[str, str | None] = {}
    for name, _args, node in literal_aliases_raw:
        doc = _statement_comment(node, types_comment_only, types_trailing, types_consumed) if node is not None else None
        literal_alias_docs[name] = _jsdoc(doc)
    typeddict_nodes = _typeddict_classes(T, types_tree)
    typeddict_names = {node.name for node, _cls in typeddict_nodes}

    # constants: types.py first (source order), then every module-level UPPER_CASE int/float/str
    # constant in envelope.py (source order there) -- e.g. the two size caps and the `t` sanity
    # bounds T_MIN_MS/T_MAX_MS. Both modules go through the same `_module_constants` scan so a new
    # constant on either side reaches both generated files with no generator change.
    constants: list[tuple[str, Any, list[str] | None]] = []
    for name, value, node in _module_constants(T, types_tree):
        doc = _statement_comment(node, types_comment_only, types_trailing, types_consumed)
        constants.append((name, value, doc))
    for name, value, node in _module_constants(E, env_tree):
        doc = _statement_comment(node, env_comment_only, env_trailing, env_consumed)
        constants.append((name, value, doc))

    # kind vocabularies. MC_KINDS/NODE_KINDS/CONTROL_CMDS/PERSISTED_EVENT_TYPES are Python `set`s --
    # sorted for determinism, since a set's own order carries no meaning. STATION_KINDS is a TUPLE:
    # its source order (respawn, powerup, extraction, bomb, control) is the advert-byte/UI mapping
    # (types.py's own comment: "Mirrors `KIND` in app/src/beacon.js"), so it is emitted AS WRITTEN,
    # never sorted. STATION_SOURCES is a `dict` (its VALUES are the human-readable descriptions) --
    # only a Python `set` needs sorting to make its order deterministic, so its keys are emitted in
    # source (insertion) order too, exactly like STATION_KINDS.
    station_kind_type_name = "StationKind" if any(n == "StationKind" for n, _ in literal_aliases) else "StationKindId"
    kind_sets: list[tuple[str, str, list[str]]] = [
        ("MC_KINDS", "McKind", sorted(T.MC_KINDS)),
        ("NODE_KINDS", "NodeKind", sorted(T.NODE_KINDS)),
        ("CONTROL_CMDS", "ControlCmd", sorted(T.CONTROL_CMDS)),
        ("PERSISTED_EVENT_TYPES", "PersistedEventType", sorted(E.PERSISTED_EVENT_TYPES)),
        ("STATION_KINDS", station_kind_type_name, list(T.STATION_KINDS)),
    ]
    station_source_ids = list(T.STATION_SOURCES)

    # PERSISTED_EVENT_TYPES's own preface (the F40/F60 "⚠ This is a WHITELIST ..." warning in
    # envelope.py) is worth carrying into the generated JS/TS same as any other symbol's comment
    # (finding #1's regression case: it used to be misattached to MAX_LOG_CHUNK_BYTES instead). The
    # other kind_sets are left alone here -- MC_KINDS in particular has per-ITEM trailing comments
    # inside its multi-line literal that are not this mechanism's concern, and reusing it for the
    # whole set risks misattaching one item's internal comment as the NEXT set's preface.
    env_nodes = _toplevel_assign_nodes(env_tree)
    _pet_node = env_nodes.get("PERSISTED_EVENT_TYPES")
    kind_set_docs: dict[str, str | None] = {
        "PERSISTED_EVENT_TYPES": _jsdoc(
            _statement_comment(_pet_node, env_comment_only, env_trailing, env_consumed)
            if _pet_node is not None else None
        ),
    }

    # interfaces
    interfaces: list[_Interface] = []
    for node, cls in typeddict_nodes:
        total = getattr(cls, "__total__", True)
        hints = get_type_hints(cls, include_extras=True)
        field_nodes = {n.target.id: n for n in node.body
                       if isinstance(n, ast.AnnAssign) and isinstance(n.target, ast.Name)}
        fields = []
        for fname, hint in hints.items():
            ctx = f"{cls.__name__}.{fname}"
            ts_type, optional = _field_type_and_optional(hint, ctx, literal_alias_by_args, typeddict_names, total)
            fnode = field_nodes.get(fname)
            doc_lines = _statement_comment(fnode, types_comment_only, types_trailing, types_consumed) if fnode is not None else None
            doc = _jsdoc(doc_lines, "  ")
            fields.append(_Field(fname, ts_type, optional, doc))
        iface_doc = _docstring_jsdoc(ast.get_docstring(node))
        interfaces.append(_Interface(cls.__name__, iface_doc, fields))

    required, event_required, accept_min = _envelope_tables(E)
    _validate_accept_min(accept_min, set(T.MC_KINDS), required)

    return _Model(
        constants=constants,
        literal_aliases=literal_aliases,
        kind_sets=kind_sets,
        station_source_ids=station_source_ids,
        interfaces=interfaces,
        required=required,
        event_required=event_required,
        accept_min=accept_min,
        literal_alias_docs=literal_alias_docs,
        kind_set_docs=kind_set_docs,
    )


def render() -> dict[pathlib.Path, str]:
    """The two generated files as they SHOULD be. Pure: reads the sources, touches nothing."""
    model = _build_model()
    return {TS_OUT: _render_ts(model), JS_OUT: _render_js(model)}


def main(argv: list[str]) -> int:
    check = "--check" in argv
    stale = []
    for path, want in render().items():
        got = path.read_text(encoding="utf-8") if path.exists() else None
        if got == want:
            continue
        stale.append(str(path.relative_to(REPO)))
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(want, encoding="utf-8")
    if check:
        if stale:
            print("STALE (run python3 mcp/tools/gen_contract.py): " + ", ".join(stale))
            return 1
        print("up to date")
        return 0
    print("wrote: " + (", ".join(stale) if stale else "nothing (already up to date)"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
