blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://open-brx.iamrossi.workers.dev/docs/
    about: Read the docs before you file a bug. They may already answer your question.
