// GENERATED by mcp/tools/gen_contract.py from mcp/brx_mcp/mc/types.py + envelope.py (+ protocol.PANIC_SEQUENCE) -- do not edit; run python3 mcp/tools/gen_contract.py

// ---- constants (types.py §9 + envelope.py's module-level constants) ----
export const ASSIST_WINDOW_MS = 4000;
export const MULTI_KILL_MS = 4000;
/** Tony 2026-09-24, ear-confirmed at volume 69: the multi-kill ladder, Halo 3's order with the two tiers the gun
 *  has no voice for (Overkill, Killpocalypse) removed, so every kill from 2 to 8 is voiced ("front stack them ...
 *  we get a sound bite on every kill"). The one table for every kill medal MC awards. `kind` multi = kills in a
 *  chain, each within MULTI_KILL_MS of the last (the HIGHEST count reached is the medal, killionaire at 8 and
 *  beyond); streak = kills without dying; first = the match's first kill. `clip` is the gun's voice line (null
 *  = no line: the HUD shows the text and the voice stays silent), `clip_ms` its length from the sound catalogue.
 *  The phone reads labels and clips from here (contract.gen MEDALS).
 *  Names (Tony 2026-09-25): each label is named after the voice line the Battle Company tagger plays for it from its
 *  own built-in sound bank. BEAT DOWN plays the bank's "Fatality" line and KILLJOY has no line (text only). Open BRX
 *  ships no audio. If a rights holder objects to a name, we will rename it. */
export const MEDALS = Object.freeze([{"key": "first_blood", "kind": "first", "count": 1, "label": "FIRST BLOOD", "clip": "VA7H", "clip_ms": 2456}, {"key": "double_kill", "kind": "multi", "count": 2, "label": "DOUBLE KILL", "clip": "VA7E", "clip_ms": 1787}, {"key": "triple_kill", "kind": "multi", "count": 3, "label": "TRIPLE KILL", "clip": "VA7Q", "clip_ms": 1904}, {"key": "killtacular", "kind": "multi", "count": 4, "label": "KILLTACULAR", "clip": "VA7M", "clip_ms": 1924}, {"key": "killtrocity", "kind": "multi", "count": 5, "label": "KILLTROCITY", "clip": "VA7O", "clip_ms": 1924}, {"key": "killamanjaro", "kind": "multi", "count": 6, "label": "KILLAMANJARO", "clip": "VA7J", "clip_ms": 1927}, {"key": "killtastrophe", "kind": "multi", "count": 7, "label": "KILLTASTROPHE", "clip": "VA7N", "clip_ms": 1924}, {"key": "killionaire", "kind": "multi", "count": 8, "label": "KILLIONAIRE", "clip": "VA7L", "clip_ms": 1924}, {"key": "killing_spree", "kind": "streak", "count": 5, "label": "KILLING SPREE", "clip": "VA7K", "clip_ms": 1924}, {"key": "unstoppable", "kind": "streak", "count": 10, "label": "UNSTOPPABLE", "clip": "VX0U", "clip_ms": 1175}, {"key": "melee_kill", "kind": "melee", "count": 1, "label": "BEAT DOWN", "clip": "VA7F", "clip_ms": 1924}, {"key": "killjoy", "kind": "killjoy", "count": 5, "label": "KILLJOY", "clip": null, "clip_ms": null}].map(r => Object.freeze(r)));
/** A63 (Tony 2026-09-24): the END-OF-MATCH awards, in recap order. `scoring.Scorer.honors()` awards them; every
 *  Honor row carries its `key`, and `award` stays the label for older consumers. None is awarded under 3 scored
 *  players. `rule` and `tie` are the rule as built, in words, for the docs and the console. A tie that survives
 *  the tie-break is SHARED: every tied player gets their own Honor row for that award. */
export const AWARDS = Object.freeze([{"key": "mvp", "label": "MVP", "rule": "top kills minus deaths; needs 1+ kill", "tie": "then K/D, then kills; still level = shared"}, {"key": "most_kills", "label": "MOST KILLS", "rule": "most kills; needs 1+ kill", "tie": "shared"}, {"key": "best_kd", "label": "BEST K/D · NON-MVP", "rule": "best K/D among players who are not MVP; needs 1+ kill", "tie": "then kills; still level = shared"}, {"key": "sharpshooter", "label": "SHARPSHOOTER", "rule": "best accuracy (hits per shot_group) with ACC_MIN_SHOTS+ shots; needs above 0 %", "tie": "shared, to the whole percent shown"}, {"key": "survivor", "label": "SURVIVOR", "rule": "the longest single life: go-live (or join, or a respawn) to a death or the match end; not for a silent player or one with a fact from an unsynced node", "tie": "shared, to the whole second; not awarded when every player ties"}, {"key": "iron_man", "label": "IRON MAN", "rule": "fewest deaths among players who played the whole match (no hot-join) and whose phone reported; must be fewer than the most", "tie": "then kills; still level = shared"}, {"key": "first_blood", "label": "FIRST BLOOD", "rule": "the match's first credited enemy kill", "tie": "none: one kill is first"}, {"key": "multikill", "label": "MULTIKILL", "rule": "the longest multi-kill chain (2+), shown with its MEDALS ladder label", "tie": "then the number of 2+ chains; still level = shared"}, {"key": "wingman", "label": "WINGMAN", "rule": "most assists; needs 1+ assist", "tie": "shared"}, {"key": "objective_hero", "label": "OBJECTIVE HERO", "rule": "koth/domination only: most seconds the player's own phone reported their team holding a point while in range (IR for a grenade, BLE for a station); needs 1+ s", "tie": "shared, to the whole second"}].map(r => Object.freeze(r)));
export const FEEDBACK_MAX_AGE_MS = 3000;
export const STATUS_HEARTBEAT_MS = 2000;
export const STALE_AFTER_MS = 8000;
/** F52: the A16.3 gun readout's timings, shipped in `gun.readout`. One owner here, so the generator emits them
 *  to the phone (contract.gen.js) and poolgauge / presentation / the stage import them: no literal copies left
 *  to disagree after a bench retune. Their meanings are documented at poolgauge.py's readout section. */
export const READOUT_LEAD_MS = 180;
export const READOUT_BLINK_GAP_MS = 80;
export const READOUT_STEP_MS = 120;
export const READOUT_BLINK_MS = 400;
export const READOUT_MIN_GAP_MS = 400;
export const READOUT_HOLD_S = 4;
/** The `sync_age_ms` a LIVE row carries when MC has never heard its node in THIS process (no node bound,
 *  or MC restarted mid-match and the phone has not spoken since). It is a sentinel, not an age: the
 *  console must print "not heard", never "11d13h ago" (visual QA H3, 2026-09-23). */
export const NEVER_SEEN_MS = 1000000000;
/** A24/M2: how far apart two cap-reaching kills may be and still count as the SAME moment. contracts.md
 *  §7 gives no single number -- it says phone clocks "drift <<1 s over a match" after a lobby re-sync, so
 *  1 s is the width of the band inside which MC cannot tell which of two kills landed first. Two players
 *  reaching the frag cap inside it are reported as a TIE rather than decided by MC's arrival order. */
export const CLOCK_TIE_MS = 1000;
/** F119: the smallest shot count an accuracy number is worth believing. Hits arrive per EVENT and shots
 *  only on the ~2 s status heartbeat, so a row with a handful of shots swings wildly between samples and
 *  can read over 100 %. `honors()` already refused SHARPSHOOTER below this; `ScoreRow.acc_provisional`
 *  now says the same thing about the live number instead of leaving the UI to guess. */
export const ACC_MIN_SHOTS = 10;
/** Past this, a node has not merely gone quiet — it is gone (phone asleep, app closed, gear packed
 *  away). Everything else the board would say about it (gun link lost, clock unsynced, wrong wi-fi,
 *  screen off) is a CONSEQUENCE of that, and listing them as separate faults turns a switched-off
 *  tagger into a wall of red alarms (field 2026-09-02). */
export const OFFLINE_AFTER_MS = 600000;
export const SYNC_FRESH_MS = 10000;
/** A32: how long `status.preflight.gun_linked` must stay TRUE CONTINUOUSLY before the link itself is
 *  accepted as proof that a headset is attached. A gun with NO headset accepts a BLE link and answers a
 *  `$PING`, then drops it within ~6 s (manual/hardware.md, manual/dev.md); switching a linked headset off
 *  makes the gun send `$DISCONNECT,*` and drop the same way. So a link that SURVIVES is the headset --
 *  10 s is the ~6 s drop plus margin for a slow phone and the ~2 s status heartbeat. Shorter and a
 *  headless gun's dying link would read as proven; much longer and the board sits amber for no reason. */
export const HEADSET_LINK_PROOF_MS = 10000;
export const LATE_ARM_GRACE_MS = 8000;
export const CONFIG_TTL_MS = 1800000;
/** wire ids 1..63; 0 reserved (tutorial / unknown shooter) */
export const MAX_PLAYERS = 63;
/** F366 (Tony 2026-09-25): a gamertag is at most MAX_TAG_LEN characters after trim + upper-case; MC refuses a
 *  longer one (never a silent cut). Past SOFT_TAG_LEN the console warns that the phone HUD may shorten it. */
export const MAX_TAG_LEN = 16;
export const SOFT_TAG_LEN = 12;
export const DEATH_LATCH_MS = 2000;
/** A34: a phone still LIVE in a match MC has retired is told `control{end}` from its status heartbeat; this
 *  is how long MC waits before telling the SAME phone about the SAME match again (the first end normally lands). */
export const STALE_LIVE_RETELL_MS = 10000;
/** A36: how long after a life begins MC waits before believing the pool a gun reports. The `$SPAWN`
 *  and the head's `$PSET` are two BLE writes and a relay apart, and the ~2 s status heartbeat can be
 *  sampled between them -- so the first frame or two of a life legitimately carries the previous
 *  pool. Past this the gun has had a whole heartbeat to settle and a pool that still disagrees with
 *  the pushed `$PSET` is the gun running a different game. */
export const POOL_CHECK_SETTLE_MS = 2000;
export const RESYNC_PROBE_S = 10;
/** Tony 2026-09-25: "default countdown 30s. 120s is generally too long." The ONE default for a START
 *  with no runway_s (api.py start/reschedule, state.py Session.start, the console's runway.ts and the
 *  generated contract all read this one constant). An explicit runway a host passes is unaffected. */
export const DEFAULT_RUNWAY_S = 30;
export const PROTOCOL_V = 1;
/** The venue volume (field-corrected 2026-08-30: 80 = on-gun L3 indoors, 90 = L4 outdoors) and the
 *  bounds of the host's per-game knob, `GameConfig.volume`. The floor is on-gun L1: 30 is inaudible
 *  for game audio, so the knob cannot choose silence. */
export const VENUE_VOLUME_INDOOR = 80;
export const VENUE_VOLUME_OUTDOOR = 90;
export const GAME_VOLUME_MIN = 60;
export const GAME_VOLUME_MAX = 100;
/** pieces.json (`pieces.PieceStore`) */
export const PIECES_STORE_V = 1;
/** favourites.json (`favourites.FavouriteStore`) */
export const FAVOURITES_STORE_V = 1;
/** the session snapshot (`state.Session` persist) */
export const SESSION_STORE_V = 1;
/** O13: the oldest StickS3 firmware MC accepts, in the Stick's own scheme `h<hardware gen>-<major>.<minor>` (its
 *  `app_ver` is `<that>+<short git sha>`, `mc_link_glue.h`). Bump it with `stationAppVer` there when a Stick
 *  change is one MC needs. "h8-0.2" is the first build that reports the git sha and `nvs_fail`: a Stick that
 *  reports plain "h8-0.1" cannot say what it runs, so it must be reflashed. */
export const STATION_MIN_FW = 'h8-0.2';
/** Exported through `gen_contract` so the console (`api/derive.ts`) and its `?mock` backend read the SAME words instead
 *  of keeping a hand copy that can drift. Every line reads `WHAT IS WRONG: WHAT TO DO` (F221; `test_mc_alert_wording.py`).
 *  The four proof prefixes whose cure is the push itself (A36/A37): a re-push replaces them (`state.cured_by_push`). */
export const STALE_ACK_FAULT = 'ACKED AN OLDER CONFIG';
export const ECHO_FAULT = 'GUN ECHO ≠ CONFIG';
export const POOL_FAULT = 'GUN POOL ≠ CONFIG';
export const GUN_CONFIG_FAULT = 'GUN CONFIG ≠ PUSHED HEAD';
/** Bench 2026-09-17: the readiness amber while the phone reports `preflight.gun_flapping` (headset off). */
export const GUN_FLAPPING_LINE = 'HEADSET OFF (GUN KEEPS DROPPING THE LINK): TURN THE HEADSET ON';
export const GUN_LINK_LOST = 'GUN LINK LOST: CHECK THE GUN IS ON AND RECONNECT IT';
export const STATION_REARM = 'RE-ARM IT FROM ITEMS ON ARMORY';
export const STATION_BRING_BACK = 'NOT RE-ARMED, OUT OF WI-FI RANGE: BRING IT BACK TO RE-ARM';
export const STATION_ARMED_OLDER = 'ARMED FOR AN OLDER GAME: RE-ARM IT FROM ITEMS ON ARMORY';
export const STATION_NOT_ARMED = 'PHONE SAYS NOT ARMED: RE-ARM IT FROM ITEMS ON ARMORY';
export const STATION_BATTERY_LOW = 'BATTERY LOW: CHARGE OR SWAP IT BEFORE THE WHISTLE';
export const TIMED_PROTECT_S_DEFAULT = 0;
export const WEAPON_DELAY_MS_DEFAULT = 500;
export const STATION_PROTECT_S_DEFAULT = 2;
/** A58: the station tamper lock (`station_config.lock_s`). The LOAD value covers a lobby wait of up to
 *  STATION_LOCK_LOBBY_S plus the match, because a muster station hears nothing after the lobby push. */
export const STATION_LOCK_MAX_S = 7200;
export const STATION_LOCK_LOBBY_S = 1800;
export const STATION_LOCK_MARGIN_S = 120;
/** a boot instant (t_recv - uptime_s) that moves further than this is a new boot */
export const STATION_REBOOT_SLACK_MS = 5000;
/** timed: the trigger goes live at least this long after protection ends */
export const TRIGGER_AFTER_PROTECT_MS = 500;
/** a death this soon after a timed respawn raises the down-screen warning */
export const SPAWN_KILL_WINDOW_MS = 10000;
/** A6 (architecture review #4, 2026-10-04): the ONE table of station presence defaults, per platform and kind. A station
 *  whose `station_config.threshold` is 0 measures (and advertises in byte 14) its platform's value here. Generated into
 *  contract.gen.ts/.js and hardware/m5sticks3/contract.gen.h, so the phone (beacon.js), the console (Items.tsx), the
 *  Stick (station_range.h) and MC (`stations.wire_threshold`) all read this one copy.
 *  phone respawn -70: Tony 2026-09-24, walked at 3-5 m. phone powerup -55: S58, about 30 cm, a placeholder until
 *  bench 4.11. phone control -75: F383, Tony 2026-09-27, until the outdoor walk. Any other phone kind -74.
 *  sticks3 respawn -57: Tony 2026-09-24 ("the stick actually works better"). sticks3 powerup -45: F434, Tony
 *  2026-09-28, about 30 cm. sticks3 control -75: UNPROVEN, Sitting B 2026-09-25, a 5-7 m target. Any other Stick
 *  kind takes the Stick respawn value. */
export const STATION_DEFAULT_THRESHOLD_DBM = Object.freeze({ phone: Object.freeze({ respawn: -70, powerup: -55, extraction: -74, bomb: -74, control: -75 }), sticks3: Object.freeze({ respawn: -57, powerup: -45, extraction: -57, bomb: -57, control: -75 }) });
/** A defaulted Stick HILL advertises -57 in byte 14 (the value the Stick advertised before the hill had its own default:
 *  Tony's Stick respawn walk, 2026-09-24), while the Stick itself measures players at
 *  STATION_DEFAULT_THRESHOLD_DBM["sticks3"]["control"]. Its own constant, so retuning the Stick respawn does not move it. */
export const STICK_HILL_ADVERT_THRESHOLD_DBM = -57;
/** F345: a phone station's defaults, sent explicitly instead of 0 to a phone app older than PHONE_THRESHOLD_ZERO_APP
 *  (which clamps 0 to -30 dBm). Read from the table above. */
export const PHONE_RESPAWN_THRESHOLD_DBM = -70;
export const PHONE_STATION_THRESHOLD_DBM = -74;
export const PHONE_POWERUP_THRESHOLD_DBM = -55;
export const PHONE_CONTROL_THRESHOLD_DBM = -75;
/** Cross-lane review #7: the powerup claim advert carries the station id in ONE byte, so a powerup station's id is 1..this
 *  (a respawn or hill station keeps 1..65535). MC refuses a larger one; the Stick and the phones read the same constant. */
export const POWERUP_STATION_ID_MAX = 255;
/** advert byte 9 "any team" (`TEAM_ANY` in beacon.js); a control point starts neutral */
export const STATION_TEAM_ANY = 255;
/** A7/D11 (architecture review #4): the presence and hill numbers the phone station (app/src/beacon.js, utility.js,
 *  control.js) and the Stick (hardware/m5sticks3/presence.h) must share. spec/utility.md §5d has the rules.
 *  the entry dwell a utility station applies (utility.js DEFAULTS.dwell) */
export const PRESENCE_DWELL_MS = 800;
/** F440: Tony 2026-10-02, the exit level is this far below the threshold */
export const PRESENCE_EXIT_BAND_DB = 3;
/** F440: leaving needs this long below the exit level (body shadowing, 2-5 s) */
export const PRESENCE_EXIT_GRACE_MS = 4000;
/** a player not heard for this long is gone */
export const PRESENCE_EXPIRY_MS = 4000;
/** a credible sighting counts for this long (= the silence expiry) */
export const PRESENCE_SIGHT_MS = 4000;
/** a sighting is the median of the adverts heard in this window */
export const PRESENCE_SIGHT_WINDOW_MS = 2000;
/** P-L1: the most adverts the sighting window keeps */
export const PRESENCE_SIGHT_RECENT_MAX = 64;
/** the RSSI EMA weight at one advert per PRESENCE_ALPHA_REF_MS */
export const PRESENCE_ALPHA = 0.35;
/** F452(c): the nominal advert period alpha was tuned at; the weight for a gap dt is 1 - (1 - alpha)^(min(dt, cap) / this) */
export const PRESENCE_ALPHA_REF_MS = 250;
/** F452(c), Tony 2026-10-04 option C: the longest gap the EMA credits, so a sparse phone is smoothed, not unfiltered */
export const PRESENCE_ALPHA_DT_CAP_MS = 500;
/** the raw-sample median before the EMA */
export const PRESENCE_MEDIAN_SAMPLES = 3;
/** F344 */
export const REVIVE_MARGIN_DB = 10;
/** a station's presence tick */
export const STATION_TICK_MS = 250;
/** control.js DEFAULT_CAPTURE_S */
export const HILL_CAPTURE_S = 10;
/** control.js DEFAULT_NET_CAP: the most a net difference counts for */
export const HILL_NET_CAP = 3;
/** control.js: the longest step one tick may advance the hill */
export const HILL_MAX_STEP_MS = 1000;
/** F82: control.js REFUSED_TID */
export const HILL_REFUSED_TID = 2;
/** A11 (architecture review #4): the config bounds MC enforces (`Session._merge_config`) and the console steppers stop at.
 *  time_limit_s 1..this */
export const TIME_LIMIT_MAX_S = 7200;
/** respawn.delay_s 0..this */
export const RESPAWN_DELAY_MAX_S = 600;
/** mode_params.hold_target_s 1..this */
export const HOLD_TARGET_MAX_S = 7200;
/** S-powerup-overrides (2026-09-28, Tony): ARMORY's per-station powerup override ranges (powerups.py checks them).
 *  Tony's own picks, not a protocol limit. 240, not 300: the StickS3 carries spawn_every_s in one byte. */
export const POWERUP_CHARGES_MIN = 1;
export const POWERUP_CHARGES_MAX = 4;
export const POWERUP_AMOUNT_MIN = 25;
export const POWERUP_AMOUNT_MAX = 150;
export const POWERUP_AMOUNT_STEP = 25;
export const POWERUP_SPAWN_EVERY_MIN = 30;
export const POWERUP_SPAWN_EVERY_MAX = 240;
export const POWERUP_SPAWN_EVERY_STEP = 30;
/** A9 (architecture review #4): the $SIR function classes compile.py builds by and the phone's engine reads.
 *  registers a $HIR, moves no pool */
export const SIR_NO_POOL_FNS = new Set([8, 23, 24, 25, 26, 27, 28, 31, 32, 34, 35]);
/** heals/armour/shields: a "damage" weapon here HELPS the target */
export const SIR_GRANT_FNS = new Set([9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]);
/** A67: an edit age at or above this is "the station restarted since, the time is lost". A Stick has no clock
 *  across a reboot, so it reports a LARGE age; MC's value then wins on the next `station_config`. */
export const STATION_EDIT_AGE_UNKNOWN_MS = 86400000;
/** A67 polish: MC dates an adopted station edit `t_recv - age`, later than the true edit by the uplink latency. While a
 *  field's source is "station", MC adds this to the age it sends, so the station's own edit is always the younger one
 *  and it keeps src "station" through every re-send (A58's START/END locks). */
export const ADOPT_SLACK_MS = 10000;
/** A1/A12 (architecture review #4): the team vocabulary by $TID (index 0-3), generated for the phone, the console and
 *  the Stick. F423: tid 3 is GREEN on the wire (`$TID,3`) but PAINTS and is NAMED purple everywhere a person sees it.
 *  The hex values are the --team-* CSS tokens (app/www/index.html, utility.html) and the Stick's screen; the inks are the
 *  dark text on them. MC's own console and roster (state.py TEAM_DEFS, webapp/mc/src/tokens.ts TEAM) keep their own
 *  palette: red is #ff5252 there, not #f43f5e; blue, yellow and purple match. A change to one is not a change to the other. */
export const TEAM_KEYS = Object.freeze(['red', 'blue', 'yellow', 'purple']);
export const TEAM_NAMES = Object.freeze(['RED', 'BLUE', 'YELLOW', 'PURPLE']);
export const TEAM_ABBRS = Object.freeze(['RED', 'BLU', 'YEL', 'PUR']);
export const TEAM_COLOUR_HEX = Object.freeze(['#f43f5e', '#3a86ff', '#ffd23f', '#bf4ce6']);
export const TEAM_INK_HEX = Object.freeze(['#1a0404', '#04121e', '#1a1400', '#140a1c']);
/** A12: the weapon role labels a person sees (the HUD's weapon card, the console's class tag). */
export const ROLE_LABELS = Object.freeze({ assault: 'ASSAULT', cqb: 'CLOSE RANGE', marksman: 'SNIPER', support: 'SUPPORT', power: 'HEAVY', melee: 'MELEE', sidearm: 'SIDEARM' });
/** contracts.md §5 "Size cap" (the retired net.md §8) */
export const MAX_ENVELOPE_BYTES = 65536;
/** log_data chunk cap (fits under the envelope cap) */
export const MAX_LOG_CHUNK_BYTES = 49152;
/** Plausibility window for `t` (Unix ms): reject obvious garbage (seconds instead of ms, negative,
 *  far future). A node with a wrong clock still lands inside this window; MC keeps t_recv anyway.
 *  2017-07 */
export const T_MIN_MS = 1500000000000;
/** 2096 */
export const T_MAX_MS = 4000000000000;
export const PANIC_SEQUENCE = Object.freeze(['$CLEAR,*', '$SP,99,*']);

// ---- kind vocabularies ----
export const MC_KINDS = new Set([
  'ack',
  'alert',
  'apply',
  'assign',
  'config',
  'control',
  'feedback',
  'join',
  'loadout_ack',
  'pull_log',
  'result',
  'score',
  'start',
  'station_config',
  'station_update',
  'time_res',
  'tutorial',
  'welcome',
]);
export const NODE_KINDS = new Set([
  'ack_config',
  'bind',
  'event',
  'event_batch',
  'hello',
  'loadout_browse',
  'loadout_request',
  'log_data',
  'log_offer',
  'ready',
  'station_action',
  'status',
  'time_req',
]);
export const CONTROL_CMDS = new Set([
  'abort_start',
  'end',
  'panic',
  'recall',
  'release_utility',
  'relink',
  'respawn',
  'resync',
]);
/** ⚠ This is a WHITELIST and an unlisted type is REJECTED at the socket, not ignored downstream --
 *  so a fact the phone learns to send reaches nothing until it is named here (the F40/F60 shape:
 *  both ends report healthy). `possession` is the objective-mode tally (mc/API.md, F70).
 *  A56 (S58): a player took a powerup station's item (never scored) */
export const PERSISTED_EVENT_TYPES = new Set([
  'death',
  'hit_taken',
  'operator_result',
  'pickup',
  'possession',
  'respawn',
  'team_change',
]);
export const STATION_KINDS = new Set([
  'respawn',
  'powerup',
  'extraction',
  'bomb',
  'control',
]);
/** The command words a NODE must never write to its gun, whatever a bundle or a debug panel says:
 *  persistent state, pairing, DFU, the IR word-format switch, factory tests, and `$DPLAY`, which
 *  blocks the gun's main loop with the serial port unread (the likely screamer mechanism). One
 *  source, `protocol.DENIED_COMMANDS`; the phone reads this copy from the generated contract
 *  (docs/spec/transport-hardening.md §4). */
export const NODE_DENIED_COMMANDS = new Set([
  'ASKSN',
  'BOOM',
  'BURN',
  'CDFU',
  'CLEARDEVICE',
  'DDFU',
  'DEV',
  'DPLAY',
  'DTYPE',
  'DUTY',
  'FACTORY',
  'FTST',
  'GPAIR',
  'GPAIRX',
  'HEADDFU',
  'INQ',
  'IRT',
  'MUZ',
  'PAIR',
  'PIN',
  'RESET',
  'SETUP',
  'SITE',
  'SOL',
  'TSTRNAME',
  'VIBTOGGLE',
  'ZOFF',
  'ZOM',
  'ZOMBIEKEYACTIVE',
  'ZON',
  'ZTOG',
]);
export const STATION_SOURCE_IDS = new Set([
  'grenade',
  'ir_station',
  'phone',
]);

// ---- required-field tables (mcp/brx_mcp/mc/envelope.py) ----
export const REQUIRED = {
  hello: ['node_id', 'node_type', 'app_ver', 'seq_next'],
  bind: ['node_id', 'gun_name', 'gun_tail'],
  event: [],
  event_batch: ['events'],
  status: ['node_id', 'arm_state', 'synced'],
  ack_config: ['config_id', 'ok'],
  time_req: ['t_node'],
  log_offer: ['node_id', 'bytes', 'lines'],
  log_data: ['node_id', 'seq', 'chunk', 'last'],
  ready: ['node_id', 'player_id', 'ready'],
  loadout_request: ['node_id', 'player_id', 'slot', 'kind'],
  loadout_browse: ['node_id', 'player_id', 'open'],
  station_action: ['id', 'action'],
  welcome: ['session_id', 'server_t', 'seq_hi'],
  assign: ['player', 'team', 'roster'],
  tutorial: ['frames'],
  config: ['config', 'frames', 'roster'],
  start: ['match_id', 'go_live_t', 'config_id', 'seq', 'countdown_s'],
  feedback: ['player_id', 'kind', 't'],
  control: ['cmd'],
  time_res: ['t_node', 'server_t'],
  pull_log: [],
  ack: ['seq_hi'],
  apply: ['frames'],
  loadout_ack: ['slot', 'ok'],
  score: ['player_id'],
  alert: ['kind', 'text', 'player_id', 't'],
  result: ['match_id', 'outcome', 'winner', 'rows', 'provisional', 't'],
  station_config: ['kind', 'team', 'id'],
  station_update: ['id', 'available'],
  join: ['pub', 'secret'],
};
export const EVENT_REQUIRED = {
  hit_taken: ['shooter_num', 'shooter_team', 'dmg'],
  death: ['shooter_num', 'shooter_team'],
  respawn: [],
  team_change: ['tid'],
  possession: ['hold_ms'],
  operator_result: ['cmd', 'ok'],
  pickup: ['station_id', 'item_kind'],
};
export const ACCEPT_MIN = {
  result: ['match_id'],
};
