// GENERATED by mcp/tools/gen_contract.py from mcp/brx_mcp/mc/types.py + envelope.py -- do not edit; run python3 mcp/tools/gen_contract.py

// ---- constants (types.py §9 + envelope.py's module-level constants) ----
export const ASSIST_WINDOW_MS = 4000;
export const MULTI_KILL_MS = 4000;
/** Tony 2026-09-24, ear-confirmed at volume 69: the multi-kill ladder, Halo 3's order with the two tiers the gun
 *  has no voice for (Overkill, Killpocalypse) removed, so every kill from 2 to 8 is voiced ("front stack them ...
 *  we get a sound bite on every kill"). The one table for every kill medal MC awards. `kind` multi = kills in a
 *  chain, each within MULTI_KILL_MS of the last (the HIGHEST count reached is the medal, killionaire at 8 and
 *  beyond); streak = kills without dying; first = the match's first kill. `clip` is the gun's voice line (null
 *  = no line: the HUD shows the text and the voice stays silent), `clip_ms` its length from the sound catalogue.
 *  The phone reads labels and clips from here (contract.gen MEDALS).
 *  Names (Tony 2026-09-25): each label is named after the voice line the Battle Company tagger plays for it from its
 *  own built-in sound bank. BEAT DOWN plays the bank's "Fatality" line and KILLJOY has no line (text only). Open BRX
 *  ships no audio. If a rights holder objects to a name, we will rename it. */
export const MEDALS = Object.freeze([{"key": "first_blood", "kind": "first", "count": 1, "label": "FIRST BLOOD", "clip": "VA7H", "clip_ms": 2456}, {"key": "double_kill", "kind": "multi", "count": 2, "label": "DOUBLE KILL", "clip": "VA7E", "clip_ms": 1787}, {"key": "triple_kill", "kind": "multi", "count": 3, "label": "TRIPLE KILL", "clip": "VA7Q", "clip_ms": 1904}, {"key": "killtacular", "kind": "multi", "count": 4, "label": "KILLTACULAR", "clip": "VA7M", "clip_ms": 1924}, {"key": "killtrocity", "kind": "multi", "count": 5, "label": "KILLTROCITY", "clip": "VA7O", "clip_ms": 1924}, {"key": "killamanjaro", "kind": "multi", "count": 6, "label": "KILLAMANJARO", "clip": "VA7J", "clip_ms": 1927}, {"key": "killtastrophe", "kind": "multi", "count": 7, "label": "KILLTASTROPHE", "clip": "VA7N", "clip_ms": 1924}, {"key": "killionaire", "kind": "multi", "count": 8, "label": "KILLIONAIRE", "clip": "VA7L", "clip_ms": 1924}, {"key": "killing_spree", "kind": "streak", "count": 5, "label": "KILLING SPREE", "clip": "VA7K", "clip_ms": 1924}, {"key": "unstoppable", "kind": "streak", "count": 10, "label": "UNSTOPPABLE", "clip": "VX0U", "clip_ms": 1175}, {"key": "melee_kill", "kind": "melee", "count": 1, "label": "BEAT DOWN", "clip": "VA7F", "clip_ms": 1924}, {"key": "killjoy", "kind": "killjoy", "count": 5, "label": "KILLJOY", "clip": null, "clip_ms": null}].map(r => Object.freeze(r)));
/** A63 (Tony 2026-09-24): the END-OF-MATCH awards, in recap order. `scoring.Scorer.honors()` awards them; every
 *  Honor row carries its `key`, and `award` stays the label for older consumers. None is awarded under 3 scored
 *  players. `rule` and `tie` are the rule as built, in words, for the docs and the console. A tie that survives
 *  the tie-break is SHARED: every tied player gets their own Honor row for that award. */
export const AWARDS = Object.freeze([{"key": "mvp", "label": "MVP", "rule": "top kills minus deaths; needs 1+ kill", "tie": "then K/D, then kills; still level = shared"}, {"key": "most_kills", "label": "MOST KILLS", "rule": "most kills; needs 1+ kill", "tie": "shared"}, {"key": "best_kd", "label": "BEST K/D · NON-MVP", "rule": "best K/D among players who are not MVP; needs 1+ kill", "tie": "then kills; still level = shared"}, {"key": "sharpshooter", "label": "SHARPSHOOTER", "rule": "best accuracy (hits per shot_group) with ACC_MIN_SHOTS+ shots; needs above 0 %", "tie": "shared, to the whole percent shown"}, {"key": "survivor", "label": "SURVIVOR", "rule": "the longest single life: go-live (or join, or a respawn) to a death or the match end; not for a silent player or one with a fact from an unsynced node", "tie": "shared, to the whole second; not awarded when every player ties"}, {"key": "iron_man", "label": "IRON MAN", "rule": "fewest deaths among players who played the whole match (no hot-join) and whose phone reported; must be fewer than the most", "tie": "then kills; still level = shared"}, {"key": "first_blood", "label": "FIRST BLOOD", "rule": "the match's first credited enemy kill", "tie": "none: one kill is first"}, {"key": "multikill", "label": "MULTIKILL", "rule": "the longest multi-kill chain (2+), shown with its MEDALS ladder label", "tie": "then the number of 2+ chains; still level = shared"}, {"key": "wingman", "label": "WINGMAN", "rule": "most assists; needs 1+ assist", "tie": "shared"}, {"key": "objective_hero", "label": "OBJECTIVE HERO", "rule": "koth/domination only: most seconds the player's own phone reported their team holding a point while in range (IR for a grenade, BLE for a station); needs 1+ s", "tie": "shared, to the whole second"}].map(r => Object.freeze(r)));
export const FEEDBACK_MAX_AGE_MS = 3000;
export const STATUS_HEARTBEAT_MS = 2000;
export const STALE_AFTER_MS = 8000;
/** F52: the A16.3 gun readout's timings, shipped in `gun.readout`. One owner here, so the generator emits them
 *  to the phone (contract.gen.js) and poolgauge / presentation / the stage import them: no literal copies left
 *  to disagree after a bench retune. Their meanings are documented at poolgauge.py's readout section. */
export const READOUT_LEAD_MS = 180;
export const READOUT_BLINK_GAP_MS = 80;
export const READOUT_STEP_MS = 120;
export const READOUT_BLINK_MS = 400;
export const READOUT_MIN_GAP_MS = 400;
export const READOUT_HOLD_S = 4;
/** The `sync_age_ms` a LIVE row carries when MC has never heard its node in THIS process (no node bound,
 *  or MC restarted mid-match and the phone has not spoken since). It is a sentinel, not an age: the
 *  console must print "not heard", never "11d13h ago" (visual QA H3, 2026-09-23). */
export const NEVER_SEEN_MS = 1000000000;
/** A24/M2: how far apart two cap-reaching kills may be and still count as the SAME moment. contracts.md
 *  §7 gives no single number -- it says phone clocks "drift <<1 s over a match" after a lobby re-sync, so
 *  1 s is the width of the band inside which MC cannot tell which of two kills landed first. Two players
 *  reaching the frag cap inside it are reported as a TIE rather than decided by MC's arrival order. */
export const CLOCK_TIE_MS = 1000;
/** F119: the smallest shot count an accuracy number is worth believing. Hits arrive per EVENT and shots
 *  only on the ~2 s status heartbeat, so a row with a handful of shots swings wildly between samples and
 *  can read over 100 %. `honors()` already refused SHARPSHOOTER below this; `ScoreRow.acc_provisional`
 *  now says the same thing about the live number instead of leaving the UI to guess. */
export const ACC_MIN_SHOTS = 10;
/** Past this, a node has not merely gone quiet — it is gone (phone asleep, app closed, gear packed
 *  away). Everything else the board would say about it (gun link lost, clock unsynced, wrong wi-fi,
 *  screen off) is a CONSEQUENCE of that, and listing them as separate faults turns a switched-off
 *  tagger into a wall of red alarms (field 2026-09-02). */
export const OFFLINE_AFTER_MS = 600000;
export const SYNC_FRESH_MS = 10000;
/** A32: how long `status.preflight.gun_linked` must stay TRUE CONTINUOUSLY before the link itself is
 *  accepted as proof that a headset is attached. A gun with NO headset accepts a BLE link and answers a
 *  `$PING`, then drops it within ~6 s (manual/hardware.md, manual/dev.md); switching a linked headset off
 *  makes the gun send `$DISCONNECT,*` and drop the same way. So a link that SURVIVES is the headset --
 *  10 s is the ~6 s drop plus margin for a slow phone and the ~2 s status heartbeat. Shorter and a
 *  headless gun's dying link would read as proven; much longer and the board sits amber for no reason. */
export const HEADSET_LINK_PROOF_MS = 10000;
export const LATE_ARM_GRACE_MS = 8000;
export const CONFIG_TTL_MS = 1800000;
/** wire ids 1..63; 0 reserved (tutorial / unknown shooter) */
export const MAX_PLAYERS = 63;
/** F366 (Tony 2026-09-25): a gamertag is at most MAX_TAG_LEN characters after trim + upper-case; MC refuses a
 *  longer one (never a silent cut). Past SOFT_TAG_LEN the console warns that the phone HUD may shorten it. */
export const MAX_TAG_LEN = 16;
export const SOFT_TAG_LEN = 12;
export const DEATH_LATCH_MS = 2000;
/** A34: a phone still LIVE in a match MC has retired is told `control{end}` from its status heartbeat; this
 *  is how long MC waits before telling the SAME phone about the SAME match again (the first end normally lands). */
export const STALE_LIVE_RETELL_MS = 10000;
/** A36: how long after a life begins MC waits before believing the pool a gun reports. The `$SPAWN`
 *  and the head's `$PSET` are two BLE writes and a relay apart, and the ~2 s status heartbeat can be
 *  sampled between them -- so the first frame or two of a life legitimately carries the previous
 *  pool. Past this the gun has had a whole heartbeat to settle and a pool that still disagrees with
 *  the pushed `$PSET` is the gun running a different game. */
export const POOL_CHECK_SETTLE_MS = 2000;
export const RESYNC_PROBE_S = 10;
/** Tony 2026-09-25: "default countdown 30s. 120s is generally too long." The ONE default for a START
 *  with no runway_s (api.py start/reschedule, state.py Session.start, the console's runway.ts and the
 *  generated contract all read this one constant). An explicit runway a host passes is unaffected. */
export const DEFAULT_RUNWAY_S = 30;
export const PROTOCOL_V = 1;
/** The venue volume (field-corrected 2026-08-30: 80 = on-gun L3 indoors, 90 = L4 outdoors) and the
 *  bounds of the host's per-game knob, `GameConfig.volume`. The floor is on-gun L1: 30 is inaudible
 *  for game audio, so the knob cannot choose silence. */
export const VENUE_VOLUME_INDOOR = 80;
export const VENUE_VOLUME_OUTDOOR = 90;
export const GAME_VOLUME_MIN = 60;
export const GAME_VOLUME_MAX = 100;
export const TIMED_PROTECT_S_DEFAULT = 0;
export const WEAPON_DELAY_MS_DEFAULT = 500;
export const STATION_PROTECT_S_DEFAULT = 2;
/** A58: the station tamper lock (`station_config.lock_s`). The LOAD value covers a lobby wait of up to
 *  STATION_LOCK_LOBBY_S plus the match, because a muster station hears nothing after the lobby push. */
export const STATION_LOCK_MAX_S = 7200;
export const STATION_LOCK_LOBBY_S = 1800;
export const STATION_LOCK_MARGIN_S = 120;
/** a boot instant (t_recv - uptime_s) that moves further than this is a new boot */
export const STATION_REBOOT_SLACK_MS = 5000;
/** timed: the trigger goes live at least this long after protection ends */
export const TRIGGER_AFTER_PROTECT_MS = 500;
/** a death this soon after a timed respawn raises the down-screen warning */
export const SPAWN_KILL_WINDOW_MS = 10000;
/** F345: a phone station's own threshold defaults (app/src/beacon.js RESPAWN_RSSI_DBM.phone, STATION_THRESHOLD_DBM),
 *  sent explicitly instead of 0 to a phone app older than PHONE_THRESHOLD_ZERO_APP (which clamps 0 to -30 dBm). */
export const PHONE_RESPAWN_THRESHOLD_DBM = -70;
export const PHONE_STATION_THRESHOLD_DBM = -74;
/** S58: a powerup station's ~1 ft claim range (placeholder until bench 4.11) */
export const PHONE_POWERUP_THRESHOLD_DBM = -55;
/** advert byte 9 "any team" (`TEAM_ANY` in beacon.js); a control point starts neutral */
export const STATION_TEAM_ANY = 255;
/** A67: an edit age at or above this is "the station restarted since, the time is lost". A Stick has no clock
 *  across a reboot, so it reports a LARGE age; MC's value then wins on the next `station_config`. */
export const STATION_EDIT_AGE_UNKNOWN_MS = 86400000;
/** A67 polish: MC dates an adopted station edit `t_recv - age`, later than the true edit by the uplink latency. While a
 *  field's source is "station", MC adds this to the age it sends, so the station's own edit is always the younger one
 *  and it keeps src "station" through every re-send (A58's START/END locks). */
export const ADOPT_SLACK_MS = 10000;
/** net.md §8 size cap */
export const MAX_ENVELOPE_BYTES = 65536;
/** log_data chunk cap (fits under the envelope cap) */
export const MAX_LOG_CHUNK_BYTES = 49152;
/** Plausibility window for `t` (Unix ms): reject obvious garbage (seconds instead of ms, negative,
 *  far future). A node with a wrong clock still lands inside this window; MC keeps t_recv anyway.
 *  2017-07 */
export const T_MIN_MS = 1500000000000;
/** 2096 */
export const T_MAX_MS = 4000000000000;

// ---- kind vocabularies ----
export const MC_KINDS = new Set([
  'ack',
  'alert',
  'apply',
  'assign',
  'config',
  'control',
  'feedback',
  'join',
  'loadout_ack',
  'pull_log',
  'result',
  'score',
  'start',
  'station_config',
  'station_update',
  'time_res',
  'tutorial',
  'welcome',
]);
export const NODE_KINDS = new Set([
  'ack_config',
  'bind',
  'event',
  'event_batch',
  'hello',
  'loadout_browse',
  'loadout_request',
  'log_data',
  'log_offer',
  'ready',
  'station_action',
  'status',
  'time_req',
]);
export const CONTROL_CMDS = new Set([
  'abort_start',
  'end',
  'panic',
  'recall',
  'release_utility',
  'relink',
  'respawn',
  'resync',
]);
/** ⚠ This is a WHITELIST and an unlisted type is REJECTED at the socket, not ignored downstream --
 *  so a fact the phone learns to send reaches nothing until it is named here (the F40/F60 shape:
 *  both ends report healthy). `possession` is the objective-mode tally (mc/API.md, F70).
 *  A56 (S58): a player took a powerup station's item (never scored) */
export const PERSISTED_EVENT_TYPES = new Set([
  'death',
  'hit_taken',
  'operator_result',
  'pickup',
  'possession',
  'respawn',
  'team_change',
]);
export const STATION_KINDS = new Set([
  'respawn',
  'powerup',
  'extraction',
  'bomb',
  'control',
]);
/** The command words a NODE must never write to its gun, whatever a bundle or a debug panel says:
 *  persistent state, pairing, DFU, the IR word-format switch, factory tests, and `$DPLAY`, which
 *  blocks the gun's main loop with the serial port unread (the likely screamer mechanism). One
 *  source, `protocol.DENIED_COMMANDS`; the phone reads this copy from the generated contract
 *  (docs/spec/transport-hardening.md §4). */
export const NODE_DENIED_COMMANDS = new Set([
  'ASKSN',
  'BOOM',
  'BURN',
  'CDFU',
  'CLEARDEVICE',
  'DDFU',
  'DEV',
  'DPLAY',
  'DTYPE',
  'DUTY',
  'FACTORY',
  'FTST',
  'GPAIR',
  'GPAIRX',
  'HEADDFU',
  'INQ',
  'IRT',
  'MUZ',
  'PAIR',
  'PIN',
  'RESET',
  'SETUP',
  'SITE',
  'SOL',
  'TSTRNAME',
  'VIBTOGGLE',
  'ZOFF',
  'ZOM',
  'ZOMBIEKEYACTIVE',
  'ZON',
  'ZTOG',
]);
export const STATION_SOURCE_IDS = new Set([
  'grenade',
  'ir_station',
  'phone',
]);

// ---- required-field tables (mcp/brx_mcp/mc/envelope.py) ----
export const REQUIRED = {
  hello: ['node_id', 'node_type', 'app_ver', 'seq_next'],
  bind: ['node_id', 'gun_name', 'gun_tail'],
  event: [],
  event_batch: ['events'],
  status: ['node_id', 'arm_state', 'synced'],
  ack_config: ['config_id', 'ok'],
  time_req: ['t_node'],
  log_offer: ['node_id', 'bytes', 'lines'],
  log_data: ['node_id', 'seq', 'chunk', 'last'],
  ready: ['node_id', 'player_id', 'ready'],
  loadout_request: ['node_id', 'player_id', 'slot', 'kind'],
  loadout_browse: ['node_id', 'player_id', 'open'],
  station_action: ['id', 'action'],
  welcome: ['session_id', 'server_t', 'seq_hi'],
  assign: ['player', 'team', 'roster'],
  tutorial: ['frames'],
  config: ['config', 'frames', 'roster'],
  start: ['match_id', 'go_live_t', 'config_id', 'seq', 'countdown_s'],
  feedback: ['player_id', 'kind', 't'],
  control: ['cmd'],
  time_res: ['t_node', 'server_t'],
  pull_log: [],
  ack: ['seq_hi'],
  apply: ['frames'],
  loadout_ack: ['slot', 'ok'],
  score: ['player_id'],
  alert: ['kind', 'text', 'player_id', 't'],
  result: ['match_id', 'outcome', 'winner', 'rows', 'provisional', 't'],
  station_config: ['kind', 'team', 'id'],
  station_update: ['id', 'available'],
  join: ['pub', 'secret'],
};
export const EVENT_REQUIRED = {
  hit_taken: ['shooter_num', 'shooter_team', 'dmg'],
  death: ['shooter_num', 'shooter_team'],
  respawn: [],
  team_change: ['tid'],
  possession: ['hold_ms'],
  operator_result: ['cmd', 'ok'],
  pickup: ['station_id', 'item_kind'],
};
export const ACCEPT_MIN = {
  result: ['match_id'],
};
