// GENERATED by mcp/tools/gen_contract.py from mcp/brx_mcp/mc/types.py + envelope.py -- do not edit; run python3 mcp/tools/gen_contract.py

// ---- constants ----
export const ASSIST_WINDOW_MS = 4000;
export const MULTI_KILL_MS = 4000;
export const FEEDBACK_MAX_AGE_MS = 3000;
export const STATUS_HEARTBEAT_MS = 2000;
export const STALE_AFTER_MS = 8000;
export const CLOCK_TIE_MS = 1000;
export const ACC_MIN_SHOTS = 10;
export const OFFLINE_AFTER_MS = 600000;
export const SYNC_FRESH_MS = 10000;
export const HEADSET_LINK_PROOF_MS = 10000;
export const LATE_ARM_GRACE_MS = 8000;
export const CONFIG_TTL_MS = 1800000;
export const MAX_PLAYERS = 63;
export const DEATH_LATCH_MS = 2000;
export const RESYNC_PROBE_S = 10;
export const DEFAULT_RUNWAY_S = 120;
export const PROTOCOL_V = 1;
export const STATION_TEAM_ANY = 255;
export const MAX_ENVELOPE_BYTES = 65536;
export const MAX_LOG_CHUNK_BYTES = 49152;

// ---- kind vocabularies ----
export const MC_KINDS = new Set([
  'ack',
  'alert',
  'apply',
  'assign',
  'config',
  'control',
  'feedback',
  'loadout_ack',
  'pull_log',
  'result',
  'score',
  'start',
  'station_config',
  'time_res',
  'tutorial',
  'welcome',
]);
export const NODE_KINDS = new Set([
  'ack_config',
  'bind',
  'event',
  'event_batch',
  'hello',
  'loadout_browse',
  'loadout_request',
  'log_data',
  'log_offer',
  'ready',
  'status',
  'time_req',
]);
export const CONTROL_CMDS = new Set([
  'abort_start',
  'end',
  'panic',
  'recall',
]);
export const PERSISTED_EVENT_TYPES = new Set([
  'death',
  'hit_taken',
  'possession',
  'respawn',
  'team_change',
]);
export const STATION_KINDS = new Set([
  'respawn',
  'powerup',
  'extraction',
  'bomb',
  'control',
]);
export const STATION_SOURCE_IDS = new Set([
  'grenade',
  'ir_station',
  'phone',
]);

// ---- required-field tables ----
export const REQUIRED = {
  hello: ['node_id', 'node_type', 'app_ver', 'seq_next'],
  bind: ['node_id', 'gun_name', 'gun_tail'],
  event: [],
  event_batch: ['events'],
  status: ['node_id', 'arm_state', 'synced'],
  ack_config: ['config_id', 'ok'],
  time_req: ['t_node'],
  log_offer: ['node_id', 'bytes', 'lines'],
  log_data: ['node_id', 'seq', 'chunk', 'last'],
  ready: ['node_id', 'player_id', 'ready'],
  loadout_request: ['node_id', 'player_id', 'slot', 'kind'],
  loadout_browse: ['node_id', 'player_id', 'open'],
  welcome: ['session_id', 'server_t', 'seq_hi'],
  assign: ['player', 'team', 'roster'],
  tutorial: ['frames'],
  config: ['config', 'frames', 'roster'],
  start: ['match_id', 'go_live_t', 'config_id', 'seq', 'countdown_s'],
  feedback: ['player_id', 'kind', 't'],
  control: ['cmd'],
  time_res: ['t_node', 'server_t'],
  pull_log: [],
  ack: ['seq_hi'],
  apply: ['frames'],
  loadout_ack: ['slot', 'ok'],
  score: ['player_id'],
  alert: ['kind', 'text', 'player_id', 't'],
  result: ['match_id', 'outcome', 'winner', 'rows', 'provisional', 't'],
  station_config: ['kind', 'team', 'id'],
};
export const EVENT_REQUIRED = {
  hit_taken: ['shooter_num', 'shooter_team', 'dmg'],
  death: ['shooter_num', 'shooter_team'],
  respawn: [],
  team_change: ['tid'],
  possession: ['hold_ms'],
};
export const ACCEPT_MIN = {
  result: ['match_id'],
};
