// GENERATED by mcp/tools/gen_contract.py from mcp/brx_mcp/mc/types.py + envelope.py -- do not edit; run python3 mcp/tools/gen_contract.py

// ---- constants (types.py §9 + envelope.py's module-level constants) ----
export declare const ASSIST_WINDOW_MS: 4000;
export declare const MULTI_KILL_MS: 4000;
export declare const FEEDBACK_MAX_AGE_MS: 3000;
export declare const STATUS_HEARTBEAT_MS: 2000;
export declare const STALE_AFTER_MS: 8000;
/** A24/M2: how far apart two cap-reaching kills may be and still count as the SAME moment. contracts.md
 *  §7 gives no single number -- it says phone clocks "drift <<1 s over a match" after a lobby re-sync, so
 *  1 s is the width of the band inside which MC cannot tell which of two kills landed first. Two players
 *  reaching the frag cap inside it are reported as a TIE rather than decided by MC's arrival order. */
export declare const CLOCK_TIE_MS: 1000;
/** F119: the smallest shot count an accuracy number is worth believing. Hits arrive per EVENT and shots
 *  only on the ~2 s status heartbeat, so a row with a handful of shots swings wildly between samples and
 *  can read over 100 %. `honors()` already refused SHARPSHOOTER below this; `ScoreRow.acc_provisional`
 *  now says the same thing about the live number instead of leaving the UI to guess. */
export declare const ACC_MIN_SHOTS: 10;
/** Past this, a node has not merely gone quiet — it is gone (phone asleep, app closed, gear packed
 *  away). Everything else the board would say about it (gun link lost, clock unsynced, wrong wi-fi,
 *  screen off) is a CONSEQUENCE of that, and listing them as separate faults turns a switched-off
 *  tagger into a wall of red alarms (field 2026-09-02). */
export declare const OFFLINE_AFTER_MS: 600000;
export declare const SYNC_FRESH_MS: 10000;
/** A32: how long `status.preflight.gun_linked` must stay TRUE CONTINUOUSLY before the link itself is
 *  accepted as proof that a headset is attached. A gun with NO headset accepts a BLE link and answers a
 *  `$PING`, then drops it within ~6 s (manual/hardware.md, manual/dev.md); switching a linked headset off
 *  makes the gun send `$DISCONNECT,*` and drop the same way. So a link that SURVIVES is the headset --
 *  10 s is the ~6 s drop plus margin for a slow phone and the ~2 s status heartbeat. Shorter and a
 *  headless gun's dying link would read as proven; much longer and the board sits amber for no reason. */
export declare const HEADSET_LINK_PROOF_MS: 10000;
export declare const LATE_ARM_GRACE_MS: 8000;
export declare const CONFIG_TTL_MS: 1800000;
/** wire ids 1..63; 0 reserved (tutorial / unknown shooter) */
export declare const MAX_PLAYERS: 63;
export declare const DEATH_LATCH_MS: 2000;
/** A34: a phone still LIVE in a match MC has retired is told `control{end}` from its status heartbeat; this
 *  is how long MC waits before telling the SAME phone about the SAME match again (the first end normally lands). */
export declare const STALE_LIVE_RETELL_MS: 10000;
/** A36: how long after a life begins MC waits before believing the pool a gun reports. The `$SPAWN`
 *  and the head's `$PSET` are two BLE writes and a relay apart, and the ~2 s status heartbeat can be
 *  sampled between them -- so the first frame or two of a life legitimately carries the previous
 *  pool. Past this the gun has had a whole heartbeat to settle and a pool that still disagrees with
 *  the pushed `$PSET` is the gun running a different game. */
export declare const POOL_CHECK_SETTLE_MS: 2000;
export declare const RESYNC_PROBE_S: 10;
export declare const DEFAULT_RUNWAY_S: 120;
export declare const PROTOCOL_V: 1;
/** advert byte 9 "any team" (`TEAM_ANY` in beacon.js); a control point starts neutral */
export declare const STATION_TEAM_ANY: 255;
/** net.md §8 size cap */
export declare const MAX_ENVELOPE_BYTES: 65536;
/** log_data chunk cap (fits under the envelope cap) */
export declare const MAX_LOG_CHUNK_BYTES: 49152;
/** Plausibility window for `t` (Unix ms): reject obvious garbage (seconds instead of ms, negative,
 *  far future). A node with a wrong clock still lands inside this window; MC keeps t_recv anyway.
 *  2017-07 */
export declare const T_MIN_MS: 1500000000000;
/** 2096 */
export declare const T_MAX_MS: 4000000000000;

// ---- Literal aliases ----
export type ArmState = 'idle' | 'connected' | 'kitted' | 'lobby' | 'armed' | 'live';
/** The MC session's own phase vocabulary. The SERVER owns it: `state.py PHASES = get_args(Phase)` is the
 *  tuple every phase guard tests against, and the console's `Phase` is generated from this alias, so a new
 *  phase cannot reach one side without the other. */
export type Phase = 'muster' | 'build' | 'kit' | 'lobby' | 'armed' | 'live' | 'recap';
export type WinBy = 'kills' | 'survival' | 'objective';
/** `policy.CHOICES` -- who fills a slot. `policy._check_rule` refuses anything else (and refuses "off"
 *  for the primary: a player with no primary weapon has nothing to play with). */
export type SlotChoice = 'player' | 'host' | 'fixed' | 'off';
/** `policy.PRIMARY_KINDS` / `SEC_KINDS` / `PERK_KINDS` together. A POLICY kind, never a request kind: a
 *  pistol is a "weapon" on the wire, and "sidearm" (A12) narrows a weapon slot to the sidearm-tagged rows. */
export type ItemKind = 'weapon' | 'perk' | 'sidearm';
/** `policy.PRESET_NAMES` -- the named rulesets, plus "custom" for a hand-edited one. */
export type LoadoutPreset = 'open' | 'no_heavies' | 'snipers' | 'custom';
export type PoolEmptyCode = 'off' | 'fixed_missing' | 'only_ids_missing' | 'needs_secondary' | 'unplayable' | 'filtered';
/** A13 / spec/utility.md §5: what a utility phone can be. Mirrors `KIND` in `app/src/beacon.js` (the advert
 *  byte 8) and `KIND_LABEL` in `app/src/utility.js`; a `station_config` naming anything else is refused at PUT. */
export type StationKind = 'respawn' | 'powerup' | 'extraction' | 'bomb' | 'control';
export type TunnelStatus = 'off' | 'starting' | 'up' | 'error';
export type TunnelProviderValue = 'cloudflared' | 'manual';
/** 2026-09-16: the PRE-ARM CHECK's ACKED cell. `none` = no head pushed for this lobby; `waiting` = pushed,
 *  no answer yet (never a fault); `failed` = refused ack, offline or unbound phone, or no answer in time. */
export type SyncAckState = 'acked' | 'waiting' | 'failed' | 'none';
/** A47: the three operator actions MC may send to ONE bound player phone (`state.py operator_action`). */
export type OperatorCmd = 'resync' | 'respawn' | 'relink';

// ---- kind vocabularies ----
export declare const MC_KINDS: ReadonlySet<McKind>;
export type McKind = 'ack' | 'alert' | 'apply' | 'assign' | 'config' | 'control' | 'feedback' | 'join' | 'loadout_ack' | 'pull_log' | 'result' | 'score' | 'start' | 'station_config' | 'time_res' | 'tutorial' | 'welcome';
export declare const NODE_KINDS: ReadonlySet<NodeKind>;
export type NodeKind = 'ack_config' | 'bind' | 'event' | 'event_batch' | 'hello' | 'loadout_browse' | 'loadout_request' | 'log_data' | 'log_offer' | 'ready' | 'status' | 'time_req';
export declare const CONTROL_CMDS: ReadonlySet<ControlCmd>;
export type ControlCmd = 'abort_start' | 'end' | 'panic' | 'recall' | 'release_utility' | 'relink' | 'respawn' | 'resync';
/** ⚠ This is a WHITELIST and an unlisted type is REJECTED at the socket, not ignored downstream --
 *  so a fact the phone learns to send reaches nothing until it is named here (the F40/F60 shape:
 *  both ends report healthy). `possession` is the objective-mode tally (mc/API.md, F70).
 *  A47: the phone's answer to an operator action (never scored) */
export declare const PERSISTED_EVENT_TYPES: ReadonlySet<PersistedEventType>;
export type PersistedEventType = 'death' | 'hit_taken' | 'operator_result' | 'possession' | 'respawn' | 'team_change';
export declare const STATION_KINDS: ReadonlySet<StationKind>;
/** The command words a NODE must never write to its gun, whatever a bundle or a debug panel says:
 *  persistent state, pairing, DFU, the IR word-format switch, factory tests, and `$DPLAY`, which
 *  blocks the gun's main loop with the serial port unread (the likely screamer mechanism). One
 *  source, `protocol.DENIED_COMMANDS`; the phone reads this copy from the generated contract
 *  (docs/spec/transport-hardening.md §4). */
export declare const NODE_DENIED_COMMANDS: ReadonlySet<NodeDeniedCommand>;
export type NodeDeniedCommand = 'ASKSN' | 'BOOM' | 'BURN' | 'CDFU' | 'CLEARDEVICE' | 'DDFU' | 'DEV' | 'DPLAY' | 'DTYPE' | 'DUTY' | 'FACTORY' | 'FTST' | 'GPAIR' | 'GPAIRX' | 'HEADDFU' | 'INQ' | 'IRT' | 'MUZ' | 'PAIR' | 'PIN' | 'RESET' | 'SETUP' | 'SITE' | 'SOL' | 'TSTRNAME' | 'VIBTOGGLE' | 'ZOFF' | 'ZOM' | 'ZOMBIEKEYACTIVE' | 'ZON' | 'ZTOG';
export declare const STATION_SOURCE_IDS: ReadonlySet<StationSourceId>;
export type StationSourceId = 'grenade' | 'ir_station' | 'phone';

// ---- shapes (mcp/brx_mcp/mc/types.py TypedDicts) ----
export interface BleId {
  address?: string;
  uuid?: string;
  tail?: string;
}

export interface ArmoryRecord {
  gun_id: string;
  sticker: string;
  headset_pin: string;
  ble: BleId;
  gen: 'gen2_3' | 'gen1';
  fw: string | null;
  labeled: boolean;
  notes?: string;
}

export interface ScanRow {
  tail: string;
  name: string;
  basename: string;
  gun_id: string | null;
  rssi: number;
  identity: 'ok' | 'unconfirmed' | 'reverted' | 'unknown';
  t: number;
}

export interface WeaponSel {
  weapon_id: string;
}

/** Per-player accessibility + HP/armour handicap (modes §1.1). All keys are optional and
 *  independent -- `state.py _check_loadout` drops the whole `overrides` key when none survive
 *  validation. S50 (2026-09-17): `easy_reload` moved HERE from the perk slot, because it is
 *  accessibility (a player who cannot work the reload lever), not balance, so a left-handed player
 *  can take it with NO extra health, and a younger player can take it WITH one (Tony, 2026-09-17:
 *  "keep the two accessibility switches independent"). */
export interface LoadoutOverrides {
  /** 1..999 (`state.py _check_loadout`); 0 is a corpse, not a pool */
  max_hp?: number;
  /** 0..999 -- 0 is legal and means "one shot with a sniper" */
  max_armor?: number;
  /** ALT button = RELOAD ($BMAP,1,97); still can't ride with a second weapon or */
  easy_reload?: boolean;
}

/** weapons[] is canonical: [primary] or [primary, secondary]; `perk` is its OWN slot and rides
 *  beside a secondary weapon (AR + pistol + Quick Switch). The one exception: S50 (2026-09-17)
 *  moved it from a perk to `overrides.easy_reload` (a per-player accessibility switch, host-set
 *  only) -- it still takes the ALT button, so the server refuses it beside a second weapon; the
 *  host UI warns and drops the other one (A14, loadout.md §2/§2.1). */
export interface Loadout {
  /** [primary] or [primary, secondary]; index == gun slot; NEVER empty (A10) */
  weapons: WeaponSel[];
  /** A14: the perk slot — rides beside a secondary weapon (loadout.md §2) */
  perk?: string | null;
  overrides?: LoadoutOverrides;
}

export interface Team {
  team_id: string;
  name: string;
  color: string;
  tid: number;
}

export interface Player {
  player_id: string;
  /** 1..63 on the wire ($PSET token 1); 0 reserved */
  player_num: number;
  display: string;
  team_id: string | null;
  node_id: string | null;
  gun_id: string | null;
  loadout: Loadout;
  voice: string;
  ready: boolean;
  /** A15 (optional): {role: sound id} picks for the $PSET voice fields + the kill line -- WHICH death scream /
   *  pain line / respawn cry of the family the gun plays (voices.PSET_ROLES + "kill"). Absent = the family defaults. */
  voice_slots?: Record<string, string>;
}

export interface RosterEntry {
  player_id: string;
  player_num: number;
  display: string;
  team_id: string | null;
}

export interface Respawn {
  type: 'auto' | 'scanner' | 'none';
  delay_s: number;
}

export interface Scoring {
  frag_limit: number | null;
  win_by: WinBy;
}

export interface Health {
  max_hp: number;
  max_armor: number;
}

/** S14: heal the killer on each kill (Fortnite/CoD "health on kill").
 *
 *  Both are **added** to the killer's own pool and clamped by the gun ($LIFE is additive-clamped),
 *  so they can never overfill. There is deliberately no `shield`: that pool is IR-only (P16), so a
 *  number here would be written and silently do nothing. */
export interface Siphon {
  hp: number;
  armor: number;
}

export interface SlotRule {
  choice: SlotChoice;
  /** primary/secondary: "weapon" | "sidearm" (A12); the perk rule is always ["perk"] (A14) */
  kinds: ItemKind[];
  exclude_tags: string[];
  exclude_ids: string[];
  only_ids: string[];
  fixed_id: string | null;
}

/** A14: `perk` is the third rule (kinds always ['perk']; choice may be 'off'). No legacy shape
 *  is supported (Tony 2026-09-04). */
export interface LoadoutPolicy {
  preset: LoadoutPreset;
  hud_select: boolean;
  primary: SlotRule;
  secondary: SlotRule;
  /** A14: perks are their own slot (choice may be "off") */
  perk: SlotRule;
}

/** allowed ids per slot, catalog order, computed server-side (loadout.md §3.2); `perks` is the
 *  perk slot's list (A14). */
export interface LoadoutPool {
  primary: string[];
  secondary_weapons: string[];
  /** A14: the perk slot's pool */
  perks: string[];
  reasons?: Record<string, PoolEmptyCode>;
}

/** The effect knobs the compiler acts on -- exactly `perks.EFFECT_KEYS`, which `PerkCatalog.__init__`
 *  refuses a perks.json row for exceeding. Every key is optional: a row carries only what it changes.
 *
 *  S50 (2026-09-17, docs/perk-design.md §2): `max_armor_add` is a FLAT armour grant/cost (body_armor
 *  +25, quick_switch -20) -- `compile._MAX_ARMOR_ADD` is the one table the compiled arithmetic reads,
 *  keyed by perk_id; this field is its wire-visible documentation, kept an integer because
 *  `app/src/hud/hud.js` / `webapp/mc/src/screens/Kit.tsx` render it literally. */
export interface PerkEffects {
  /** added to $PSET armour (or, base armour 0: $PSET shield) -- capped at 255, */
  max_armor_add?: number;
  /** floored at 0 (`compile.armed_armor`/`armed_shield`)
   *  scales the clip/reserve the head writes */
  ammo_mult?: number;
  /** scales the weapon's reload time */
  reload_mult?: number;
  /** unused by any current row (S50: easy_reload moved to */
  alt_reload?: boolean;
  /** `loadout.overrides.easy_reload`) -- kept for a future ALT-button perk
   *  scales $WEAP tok15, the gun's swap delay (bench 2026-09-04) */
  switch_mult?: number;
  /** S50 (new, armor_piercing perk): primary's $SIR key -> the armour-piercing */
  armor_piercing?: boolean;
}

export interface PerkView {
  perk_id: string;
  name: string;
  desc: string;
  tags: string[];
  mechanism: 'passive' | 'slot_frame';
  effects: PerkEffects;
  verified: boolean;
  hidden: boolean;
}

/** S50 build 4: a wire number before and after a perk touched it. Integers, always both present
 *  together (never just one). */
export interface ValuePair {
  base: number;
  resolved: number;
}

/** S50 build 4 (`docs/spec/loadout.md` §1.2/§2): the RESOLVED, per-player perk effect, exactly as
 *  it was compiled into this bundle -- not the catalogue's `PerkEffects` (which is unresolved and
 *  pool-independent). A field is present only when the perk actually changed it; `perk_id` is present
 *  whenever the player carries a perk, even one with no other field here, so a phone/console can show
 *  an icon. Lives on `FrameBundle.perk_effects` (the persisted per-player config, survives an app
 *  restart) and, per player, on `State`'s roster/player view for Mission Control's console. */
export interface PerkEffectsResolved {
  perk_id?: string;
  mag?: ValuePair;
  reserve?: ValuePair;
  reload_ms?: ValuePair;
  swap_ms?: ValuePair;
  max_hp?: ValuePair;
  max_armor?: ValuePair;
  max_shield?: ValuePair;
}

/** One armed utility item on `GameConfig.stations` -- exactly what `state.py _station_ids()` builds
 *  (`{"id": a["id"], "kind": a["kind"]}`), sorted by id. Both keys are always present. */
export interface StationRef {
  id: number;
  kind: StationKind;
}

export interface Stun {
  /** F15/A20: seconds a hit EMP keeps the gun disarmed (default 10, 1..60) */
  duration_s?: number;
}

/** S42 (2026-09-17): a weapon's TARGET accuracy profile -- `weapons.json` `recoil`, declared-only
 *  on the wire (compile.py `resolve()` never writes t21/t22 from it). `app/src/engine.js` is the sole
 *  reader. **F259 (2026-09-18): a STATE MACHINE, not a per-shot walk** -- `_recoilProfile` derives
 *  `crisp`/`degraded`/`heavy` states from this shape (`ceiling`/`floor` become `crisp`/`degraded`,
 *  `per_shot` sizes `after_shots`, `recover_ms` floors `settle_ms`): CRISP until the burst reaches
 *  `after_shots` rounds (DEGRADED), HEAVY after `heavy_after_shots`, and back to CRISP in one step
 *  once the trigger is quiet for `settle_ms`. `weapons.json` still ships this old ladder shape,
 *  field for field; `docs/spec/node.md` §3.15 has the state machine's full rule table. */
export interface Recoil {
  ceiling: number;
  floor: number;
  per_shot: number;
  recover_ms: number;
}

export interface GameConfigBase {
  config_id: string;
  mode: string;
  environment: 'indoor' | 'outdoor';
  night: boolean;
  /** required (>0) on the phone path; None only for full-coverage venues */
  time_limit_s: number | null;
  respawn: Respawn;
  scoring: Scoring;
  health: Health;
  teams: Team[];
  led?: Record<string, unknown>;
  /** A6.5 */
  player_num_base?: number;
  /** S14: heal-on-kill; absent or {0,0} = off */
  siphon?: Siphon;
  /** A13.1 (F104): the utility items MC armed for THIS game, when at least one is assigned.
   *  Set by `Session._wire_config()` from the ITEMS assignments, never by the
   *  operator; a player phone honours only these ids (`engine.js _stationAllowed`) --
   *  and when the list is ABSENT (nothing assigned) it honours ANY station (the hand-armed fallback). */
  stations?: StationRef[];
  /** F70: what is emitting this game's objective -- `STATION_SOURCES` above
   *  ("grenade" = a BRX Smart Grenade in hill mode, "ir_station" = a
   *  $CAPTURE-speaking station). Present only for the modes that need one
   *  (domination/koth/ctf/cs/bomb); `validate()` refuses those without it. */
  station_source?: string;
  /** A11 (mc/presentation.py): sounds + lights per event, preset or custom */
  presentation?: Record<string, unknown>;
  /** A17: per-WEAPON $SIR sounds. DEFAULT OFF -- bench F38: a non-empty
   *  $SIR sound REPLACES the $PSET pool sound rather than layering, so
   *  turning this on SILENCES the ear-confirmed material layer (armour
   *  metal / shield fizz / silent health) on every standard hit. */
  hit_audio_class?: boolean;
  /** A17: give each weapon FAMILY its own $SIR cell so hits sound different
   *  per weapon. DEFAULT OFF -- an unmatched cell is silently ignored (the
   *  F11 shape), so it stays off until FOLLOWUPS F38/F39 clear it at the bench. */
  hit_audio_rekey?: boolean;
  /** F15/A20: the host-driven STUN (EMP). Present = the `<8,0>` $SIR cell
   *  ships as fn 24 (status, no damage) and a proto-8 $HIR disarms the
   *  victim's node for `duration_s` (default 10, 1..60). Absent = the stock
   *  charge-rifle damage row, byte-for-byte. Source: a $WEAP t3=8 slot
   *  (the charge rifle) or a proto-8 station. */
  stun?: Stun;
  /** A31/A4.8: the VENUE's radio coverage -- "full" = every phone is on
   *  the LAN for the whole match (the only case where `time_limit_s` may
   *  be null and where an MC-decided end needs no "verify at MC" warning).
   *  Absent/anything else = partial. `compile.full_coverage()` is the one
   *  reader; `opts.coverage` (the CLI/sim path) still wins. */
  coverage?: 'full' | 'partial';
  /** A18 (E1): the MODE's own rules -- what its engine declares in `PARAMS`
   *  (`modes/params.py`; schema per mode from `GET /api/modes`). Present, and
   *  COMPLETE (defaults filled), for every mode whose engine declares any;
   *  absent for one that declares none (tdm/ffa/infection), so those configs
   *  are byte-identical to before the field existed. Unknown keys and
   *  out-of-range values are refused at PUT and again by `validate()`.
   *  Rides the wire as-is: a node reads its rules from here, never from a
   *  schema of its own. */
  mode_params?: Record<string, number | boolean | string>;
  /** A19 (S10): who the VIP is. Must name a rostered player (`validate()`);
   *  MC pushes them the `vip` headset role (`alert.role`) once the match is
   *  live and again after each of their respawns. Never stored in a saved
   *  game (a preset names no person). */
  vip_player_id?: string | null;
  /** S42: node-driven recoil (the accuracy ceiling/floor is OURS, not the
   *  gun's native walk -- F230). DEFAULT ON: absent or `true` = on, only an
   *  explicit `false` turns it off. No FrameBundle change needed -- `config`
   *  already rides every push wholesale, and `app/src/engine.js` reads
   *  `config.recoil !== false`. Seam for stance/flinch (also S42, not built
   *  here): a future switch for either can sit right beside this one. */
  recoil?: boolean;
}

/** A complete config type whose policy may be omitted for server defaulting. */
export interface GameConfig {
  config_id: string;
  mode: string;
  environment: 'indoor' | 'outdoor';
  night: boolean;
  time_limit_s: number | null;
  respawn: Respawn;
  scoring: Scoring;
  health: Health;
  teams: Team[];
  led?: Record<string, unknown>;
  player_num_base?: number;
  siphon?: Siphon;
  stations?: StationRef[];
  station_source?: string;
  presentation?: Record<string, unknown>;
  hit_audio_class?: boolean;
  hit_audio_rekey?: boolean;
  stun?: Stun;
  coverage?: 'full' | 'partial';
  mode_params?: Record<string, number | boolean | string>;
  vip_player_id?: string | null;
  recoil?: boolean;
  loadout_policy?: LoadoutPolicy;
}

/** A config MC serves in State or from a successful config/preset response.
 *
 *  PUT bodies use ``GameConfig`` with optional fields, since callers may update only selected keys.
 *  Served configs have gone through the server's policy fill and always include ``loadout_policy``. */
export interface ConfigView {
  config_id: string;
  mode: string;
  environment: 'indoor' | 'outdoor';
  night: boolean;
  time_limit_s: number | null;
  respawn: Respawn;
  scoring: Scoring;
  health: Health;
  teams: Team[];
  led?: Record<string, unknown>;
  player_num_base?: number;
  siphon?: Siphon;
  stations?: StationRef[];
  station_source?: string;
  presentation?: Record<string, unknown>;
  hit_audio_class?: boolean;
  hit_audio_rekey?: boolean;
  stun?: Stun;
  coverage?: 'full' | 'partial';
  mode_params?: Record<string, number | boolean | string>;
  vip_player_id?: string | null;
  recoil?: boolean;
  loadout_policy: LoadoutPolicy;
}

export interface FrameBundle {
  config_id: string;
  player_id: string;
  /** config head, NO $SPAWN, no countdown sound; ends with $TID */
  head: string[];
  /** A44: fn-28 $SIR table -> $PLAYX,0 -> $SPAWN,, -> $AMMO... -> $BMAP,0,0; the live table is a sir_pool take written once the gun can fire */
  spawn: string[];
  revive: string[];
  end: string[];
  panic: string[];
  team_flip?: Record<string, string[]>;
  /** F86: per-tid [blank, rest] the node takes the gun with after a flip */
  team_flip_take?: Record<string, string[]>;
  /** A6.3: key -> PRE-COMPOSED frame the node writes verbatim. countdown, kill,
   *  game_over?, victory?, tick?, klaxon?, multi?, medal?, runway_*?, and the once-per-life
   *  low-health pair hurt?/hurt_led? (hurt_led is an $HLED, not a $PLAY — see compile.cues)
   *  A11: plus one key per presentation EVENT that carries a sound (hit_taken … vip_down); "" = deliberately mute.
   *  A15.2: `spawn` = the character's spawn line, written by the node IMMEDIATELY after the spawn / revive frames
   *  (the head's $PSET ships an empty battleRespawnCry, so the firmware itself says nothing on $SPAWN).
   *  A15.3: `pain_short` / `pain_long` / `pain_melee` = the pain the node plays on a $HIR (the $PSET pain fields ship
   *  empty): a melee word -> pain_melee; damage >= voice.pain_long_min -> pain_long; else pain_short. At most one per
   *  600 ms, none on the lethal hit (the firmware's death scream covers it). */
  cues: Record<string, string>;
  /** A11: event -> [[frame, hold_s], ...] -- the tuned $GLED burst (+ optional $HLED) */
  leds?: Record<string, unknown[]>;
  /** A11: presentation.summary() -- preset + switches, for the UI/HUD */
  presentation?: PresentationSummary;
  /** A11.7: {in_play team|dark|health, blank, rest, bands?[[frac,f]]} -- absent for native */
  gun?: Record<string, unknown>;
  /** A11.6: {in_play, rest, blank, pregame[], start[[f,s]], hit[[f,s]], death[[f,s]], respawn[[f,s]], carrier{tid:[[f,s]]}} */
  headset?: Record<string, unknown>;
  /** 2026-09-04: the weapon-swap delay the gun enforces (max tok15 of slots 0/1, after perks) */
  swap_ms?: number;
  /** A15.1: event -> frames; the node picks ONE at random per event; `cues[ev]` is the deterministic first */
  cue_pools?: Record<string, string[]>;
  /** A15: {id, family, pset{role: id}, kill, rolled{role: id} (A15.1: this push's draws), pools{role: [ids]},
   *  spawn: [ids] (A15.2: the spawn pool; `pset.respawn_cry` is "" unless picked),
   *  pset_pool: [death-scream ids, one per `pset_pool` frame], pain_long_min: int} (A15.3) */
  voice?: Record<string, unknown>;
  /** A15.3: the node writes ONE of these at random immediately before every `$SPAWN` (spawn and revive),
   *  so the firmware's death scream changes per life. One full $PSET per death-scream take; only the
   *  deathScream token differs. A pinned `death_scream` (or a one-take family) = one frame = head[4].
   *  A17: each take ALSO carries its own hitHp/hitArrmor/hitShield/hitCrit draw (hitaudio.MATERIAL_POOLS). */
  pset_pool?: string[];
  /** A17/A44: one full live `$SIR` table per take, the ONLY live carrier -- the node writes one once the gun can fire after every spawn/revive, and again after a
   *  lull, so the same weapon does not land the same clip all match. Re-sending `$SIR` rows is the F11 repair
   *  path, so the write is safe by construction; the rows are identical apart from their sound tokens. */
  sir_pool?: string[][];
  /** A17: {rekey: bool, cells{weapon_id: "p,s"}, classes{"p,s": family}, shared[families sharing a cell],
   *  material[roles]} -- what the UI/console shows for "what does a hit sound like", and what a bench probe reads. */
  hit_audio?: Record<string, unknown>;
  /** S50 build 4: this player's compiled perk effect,
   *  absent when they carry no perk. Persisted here (not a
   *  one-shot message) so it survives an app restart. */
  perk_effects?: PerkEffectsResolved;
}

export interface Weapon {
  weapon_id: string;
  name: string;
  cls: string;
  /** ballistic|energy|melee (weapons.json `class`, A10, 2026-09-17): ballistic reloads, energy overheats/charges; not the same as `cls` above (raw protocol class byte) */
  weapon_class: string;
  /** house-written armory blurb (weapons.json `desc`); "" if a row lacks one */
  desc?: string;
  stats: Record<string, unknown>;
  weap_frame: string;
  icon?: string;
  verified?: boolean;
  /** A10 policy vocabulary (loadout.md §1.1) */
  tags?: string[];
  role?: string;
  /** A10: human copy for a known LIVE problem (weapons.json `caution`) */
  caution?: string;
  /** 2026-09-17: catalogue-visible but never in a player loadout pool (policy.py) */
  pickup_only?: boolean;
  /** S42: the declared target accuracy profile (weapons.json `recoil`) */
  recoil?: Recoil;
  /** A48: rounds of the cell one FULL charge spends. `WeaponCatalog.rounds_per_charge()` resolves weapons.json's absent-means-1 row to a concrete integer, so a real compiled Weapon always carries this; NotRequired only for a hand-built fixture that skips it */
  rounds_per_charge?: number;
  /** 2026-09-18, weapon-design.md §7.4: False = cannot kill; absent means true */
  lethal?: boolean;
  /** F62 (2026-09-18): $WEAP t6 primaryCritChance, 0-100; absent = never crits */
  crit_pct?: number;
}

export interface WeaponBars {
  power: number | null;
  rof: number | null;
  ammo: number | null;
  ttk: number | null;
}

/** Host-health-ranked arsenal row built by views.weapon_view(s). */
export interface WeaponView {
  weapon_id: string;
  name: string;
  cls: string;
  /** ballistic|energy|melee (weapons.json `class`, A10, 2026-09-17): ballistic reloads, energy overheats/charges; not the same as `cls` above (raw protocol class byte) */
  weapon_class: string;
  desc: string;
  clip: number;
  mags: number;
  reserve: number | null;
  reload_s: number | null;
  reload_ms: number | null;
  dmg: number | null;
  rpm: number | null;
  rng: number | null;
  dmg_per_hit: number | null;
  /** older MC rows predate host-pool ranking; the current producer always fills it */
  pool?: number;
  verified: boolean;
  tags: string[];
  role: string;
  htk: number | null;
  /** older MC rows can omit this derived figure */
  ttk_ms?: number | null;
  caution?: string;
  ammo_total?: number;
  bars?: WeaponBars;
  /** 2026-09-17: catalogue-visible but never in a player loadout pool (policy.py) */
  pickup_only?: boolean;
  /** 2026-09-18 (weapon-design.md §7.4): FALSE on a weapon that deliberately */
  lethal?: boolean;
  /** cannot kill (the fn-20 Breacher, the fn-23 Haze). It may never be a PRIMARY:
   *  the server refuses one in slot 0 and both UIs mirror that, so the field has
   *  to travel with the row or a console offers a pick that is refused at arming.
   *  S42: the declared target accuracy profile -- the node's `weaponRow(id).recoil` */
  recoil?: Recoil;
  /** A48: rounds of the cell one FULL charge spends -- the HUD's NOT ENOUGH ENERGY line reads this, never a hard-coded cost. `views.weapon_view()` resolves the catalogue's absent-means-1 row, so a real WeaponView always carries this; NotRequired only for a hand-built fixture that skips it */
  rounds_per_charge?: number;
  /** F62 (2026-09-18): $WEAP t6 primaryCritChance, 0-100; absent = never crits */
  crit_pct?: number;
}

/** A sanitized whole-game preset stored on the Mission Control host. */
export interface SavedGame {
  preset_id: string;
  name: string;
  desc: string;
  builtin: boolean;
  created_t: number;
  updated_t: number;
  config: GameConfig;
}

export interface Preflight {
  ssid_ok?: boolean;
  mc_reachable?: boolean;
  auto_join_ok?: boolean;
  cellular_off?: boolean;
  dnd_on?: boolean;
  phone_batt?: number;
  screen_on?: boolean;
  foreground?: boolean;
  gun_linked?: boolean;
  headset_ok?: boolean;
  /** Bench 2026-09-17: true while the gun keeps dropping the link seconds after each connect (2+ quick
   *  drops in a row, BrxLink.flapping), which is what a headset that is off looks like. Optional. */
  gun_flapping?: boolean;
}

/** One player or utility node in `State.snapshot()`.
 *
 *  `last_seen_ms` is an age in this public view. The session keeps the corresponding node record's
 *  receive timestamp internally and projects it at snapshot time, so the UI never receives the
 *  host's wall clock. The optional fields are forwarded only after the node has reported them. */
export interface NodeView {
  node_id: string;
  node_type: string;
  arm_state: ArmState;
  last_seen_ms: number;
  synced: boolean;
  gun_name?: string;
  gun_tail?: string;
  player_id?: string;
  preflight?: Preflight;
  battery?: number | null;
  fw?: string | null;
  hp?: number | null;
  armor?: number | null;
  ammo?: number | null;
  alive?: boolean | null;
  pending?: number | null;
  app_ver?: string | null;
  platform?: string | null;
  log?: LogView | null;
  reach?: 'lan' | 'backhaul';
  last_reach?: 'lan' | 'backhaul';
  /** F208: the node's last `status.pool_stale` / `pool_stale_ms`. Absent = not stale, or an older app. */
  pool_stale?: 'silent' | 'no_fire' | 'write_lost';
  pool_stale_ms?: number;
}

export interface Event {
  type?: 'hit_taken' | 'death' | 'respawn' | 'team_change' | 'status' | 'possession' | 'operator_result';
  t?: number;
  match_id?: string | null;
  node_id?: string;
  player_id?: string | null;
  /** hit_taken / death */
  shooter_num?: number;
  shooter_team?: number;
  dmg?: number;
  ir_proto?: number;
  /** $HIR tok1 — WHICH sensor caught the shot. 0-3 are ALL HEADSET sensors (the headset carries
   *  FOUR, operator-confirmed 2026-09-01; only 0 = front and 1 = back are bench-mapped), 4 = gun
   *  body. Forwarded 2026-09-01: it was parsed on the phone and dropped, so a
   *  "the headset domes never register" report could only be checked against a frame ring. */
  sensor?: number;
  desync?: boolean;
  /** respawn */
  resync?: boolean;
  /** A47: the operator's FORCE RESPAWN, not a respawn after a death (scoring keeps the streak) */
  operator?: boolean;
  /** F264: the node's OWN cure revived this player, blind, after `poolStale` said `no_fire` and the gun answered
   *  no `$QUERY`. There is no death in front of it and nobody asked for it, so the board must be able to tell it
   *  apart from a real respawn -- and a run of them is the signal that one gun needs a human. */
  auto?: boolean;
  /** operator_result (A47): what the phone DID with an operator action MC sent (`control{resync|respawn|relink}`).
   *  Persisted like every fact, and read for the operator's feed and menu only: it never reaches the scorer. */
  cmd?: OperatorCmd;
  ok?: boolean;
  /** present on a refusal: the phone's own reason ("stunned", "not live", ...) */
  why?: string;
  /** team_change */
  tid?: number;
  /** possession (F70, objective modes) — a CUMULATIVE tally for ONE control point, resent as it grows.
   *  `hold_ms` maps a TEAM TID (as a string key on the wire: JSON has no integer keys) to the ms this
   *  node observed that team OWNING the point; tid 2 on a hill is NEUTRAL, not a team. `observed_ms` is
   *  how long it could hear the point at all, which is what makes the number a stated lower bound
   *  rather than a claim. `site` is "A" for the single grenade point (F88: a beacon carries no id).
   *  MC merges these by MAX per (site, team) and NEVER by sum — see `scoring._possession`. */
  site?: string;
  hold_ms?: Record<string, number>;
  observed_ms?: number;
  source?: 'beacon' | 'station';
  /** status */
  hp?: number;
  armor?: number;
  ammo?: number;
  alive?: boolean;
  shots?: number;
  deadline_s?: number;
  battery?: number;
  fw?: string;
  arm_state?: ArmState;
  t_minus_ms?: number;
  synced?: boolean;
  dropped?: number;
  preflight?: Preflight;
  /** A37/R2-3: WHERE `hp`/`armor` above came from THIS LIFE. `engine.js` fills them from
   *  `config.health` at spawn/revive -- the phone's MODEL of the pool -- and overwrites them with the
   *  gun's own numbers on the first `$LCD`/`$HP`. The `$PSET` MC pushed bakes
   *  `loadout.overrides.max_hp/max_armor` and the body_armor perk, so the two legitimately disagree
   *  until the gun has spoken, and `state.py _check_pool` judges `"gun"` ONLY. Optional: an app that
   *  omits it makes no claim at all, and the check keeps waiting rather than guessing. */
  pool_src?: 'gun' | 'model';
  /** A36: the `config_id` of the head this node is CURRENTLY holding (`engine.js statusBody`).
   *  `ack_config` says which config a gun took at the moment it took it; this says which one it is
   *  still on, every ~2 s, for the rest of the game -- the difference that made a whole field night
   *  of stale pushes invisible. Optional: an older app omits it and MC then makes no claim. */
  config_id?: string;
  /** F208: the pool this status reports is STALE, and why. A gun that died kept a byte-identical status
   *  for 105 s and looked like a healthy idle player. `"silent"` = no gun frame for 185 s; `"no_fire"` =
   *  three trigger presses in a row got no shot back; `"write_lost"` = this life's spawn or revive write was
   *  lost and the phone did not repeat it (pl4: RESYNC GUN clears it). `pool_stale_ms` = ms since the gun last reported a
   *  pool. Absent = not stale, or an older app: MC then shows no cue at all. */
  pool_stale?: 'silent' | 'no_fire' | 'write_lost';
  pool_stale_ms?: number;
}

export interface ScoreRow {
  player_id: string;
  display: string;
  team_id: string | null;
  kills: number;
  deaths: number;
  assists: number;
  shots: number;
  hits: number;
  accuracy: number | null;
  kd: number;
  /** CURRENT streak — 0 for whoever died last. `best_streak` is the one to show. */
  streak: number;
  medals: string[];
  /** --- additive, 2026-09-11 (F116 / F119). NotRequired, not merely new: `scoring.py` fills all five on
   *  every LIVE row, but a session PERSISTED before the change replays rows without them, so a reader that
   *  assumes them crashes on last week's recap. Never read one without a fallback. ---
   *  shots incl. the pre-hot-swap baseline (A6.2); == `shots` */
  shots_total?: number;
  /** F116: the LONGEST streak this match. `streak` stayed for compatibility. */
  best_streak?: number;
  /** the biggest multi-kill (2 = double, 3 = triple, 4+ = killtacular); 0 = none */
  multi_best?: number;
  /** this player drew first blood */
  first_blood?: boolean;
  /** F119: `accuracy` is not settled yet — render it as settling, not as fact */
  acc_provisional?: boolean;
  /** 2026-09-12, the same additive rule as the five above: `scoring.rows()` fills both on every LIVE row
   *  (0 when nothing landed late) and `rows_csv` has a column for each, but a session PERSISTED before
   *  they existed replays rows without them. Kills and deaths scored AFTER the whistle (A6.1 parks them,
   *  they do not move the tally) -- read either one only with a fallback. */
  after_end_kills?: number;
  after_end_deaths?: number;
}

/** A47: the last operator action MC sent to one player, and what the phone said about it.
 *  `state` is "sent" until the phone's `operator_result` fact arrives, then "done" or "refused". With no
 *  answer OPERATOR_NO_ANSWER_MS after the send it reads "no_answer" (an older app, a dropped socket); a late
 *  answer still replaces it. For relink, "done" means the phone STARTED the relink, not that the gun is back. */
export interface OperatorStatus {
  cmd: OperatorCmd;
  state: 'sent' | 'done' | 'refused' | 'no_answer';
  why: string | null;
  sent_t: number;
  result_t: number | null;
}

export interface LiveRow {
  player_id: string;
  display: string;
  team_id: string | null;
  kills: number;
  deaths: number;
  assists: number;
  shots: number;
  hits: number;
  accuracy: number | null;
  kd: number;
  streak: number;
  medals: string[];
  shots_total?: number;
  best_streak?: number;
  multi_best?: number;
  first_blood?: boolean;
  acc_provisional?: boolean;
  after_end_kills?: number;
  after_end_deaths?: number;
  status: 'alive' | 'down' | 'stale';
  sync_age_ms: number;
  respawn_in_s: number | null;
  /** F208: the bound node's `pool_stale` / `pool_stale_ms`, as NodeView. Absent = not stale. */
  pool_stale?: 'silent' | 'no_fire' | 'write_lost';
  pool_stale_ms?: number;
  /** A47: the latest operator action for this player in THIS match. Absent = none sent. */
  operator?: OperatorStatus;
}

export interface LiveView {
  match_id: string;
  go_live_t: number;
  time_limit_s: number;
  ends_t: number;
  score: Record<string, number>;
  rows: LiveRow[];
  /** A47: an ADOPTED match only. True when every bound phone that has reported a claim says it has ended
   *  (`kitted` for this match, or another match), and at least one does. MC never ends an adopted match
   *  itself; the console asks the operator to press END. Absent = no such claim. */
  phones_ended?: boolean;
}

export interface StartNodeView {
  arm_state: ArmState;
  t_minus_ms: number | null;
  synced: boolean;
  last_seen_ms: number;
}

export interface StartView {
  match_id: string;
  go_live_t: number;
  config_id: string;
  seq: number;
  countdown_s: number;
  per_node: Record<string, StartNodeView>;
}

/** One tunable schema row served by GET /api/modes. */
export interface ModeParamSpec {
  name: string;
  type: 'int' | 'float' | 'bool' | 'str';
  default: number | boolean | string;
  desc: string;
  min?: number;
  max?: number;
  choices?: string[];
}

/** One mode catalogue row served by ``GET /api/modes``. */
export interface ModeInfo {
  mode: string;
  name: string;
  abbr: string;
  desc: string;
  brief: string;
  teams_text: string;
  win_text: string;
  respawn_text: string;
  defaults: GameConfig;
  params: ModeParamSpec[];
}

export interface Honor {
  award: string;
  player_id: string;
  stat: string;
}

export interface StationAssignment {
  kind: StationKind;
  team: number;
  id: number;
  threshold: number;
  at?: number;
}

export interface StationControl {
  owner?: number;
  progress?: number;
  contested?: boolean;
  hold_ms?: Record<string, number>;
}

export interface StationReport {
  kind?: StationKind;
  team?: number;
  station_id?: number;
  threshold?: number;
  live?: boolean;
  revives?: number;
  armed?: boolean;
  battery?: number;
  control?: StationControl;
}

export interface StationArmed {
  game: number;
  at: number;
  kind: StationKind;
  team: number;
  id: number;
}

/** A utility phone as MC sees it in the ITEMS panel. */
export interface StationView {
  node_id: string;
  assigned: StationAssignment | null;
  armed: StationArmed | null;
  arm_pending: boolean;
  report: StationReport;
  app_ver?: string | null;
  platform?: string | null;
  last_seen_ms: number | null;
  online: boolean;
  attention: string[];
  game: number;
}

/** One assigned utility station's self-authoritative recap heartbeat. */
export interface RecapStationRow {
  node_id: string;
  kind: StationKind;
  id: number;
  team: number;
  heard: boolean;
  revives?: number | null;
  hold_ms?: Record<string, number> | null;
  owner?: number | null;
}

export interface EndDeliveryRow {
  player_id: string;
  display: string;
  node_id: string;
  tries: number;
  since_ms: number;
  reached: boolean;
  retrying: boolean;
}

export interface EndDeliveryView {
  match_id: string;
  total: number;
  confirmed: number;
  unconfirmed: EndDeliveryRow[];
  retrying: boolean;
}

/** Derived socket coverage; full iff every bound player is on backhaul. */
export interface Coverage {
  level: 'full' | 'zones';
  on_backhaul: number;
  bound: number;
}

export interface LanPublic {
  ws_url: string | null;
  status: TunnelStatus;
  provider: TunnelProviderValue | null;
  available: boolean;
  detail?: string;
  error?: string;
}

export interface PresentationRow {
  event: string;
  source: 'hud' | 'mc' | 'both';
  desc: string;
  sound: string | null;
  words: string;
  gun_led: number | null;
  headset: number | null;
  flash: 'green' | null;
  slot: 'queue' | 'interrupt' | null;
  text: string;
  enabled: boolean;
}

export interface HeadsetSummary {
  pregame: string;
  start_flash: boolean;
  in_play: string;
  hit: number | null;
  death: string | number;
  respawn_flash: boolean;
  role: boolean;
  carrier: boolean;
}

export interface GunSummary {
  in_play: string;
  pregame: string;
  readout?: Record<string, unknown>;
}

export interface PresentationSummary {
  preset: string;
  announcer: boolean;
  gun_flash: boolean;
  headset_team: boolean;
  sight_flash: boolean;
  hud_events: boolean;
  mc_events: boolean;
  mc_confidence: boolean;
  blackout: boolean;
  voice: 'on' | 'hits_only' | 'off';
  headset: HeadsetSummary;
  gun: GunSummary;
  custom_events: string[];
}

export interface McConfidence {
  confident: boolean;
  missing: string[];
  stale: string[];
  unflushed: string[];
}

export interface PresentationView {
  summary: PresentationSummary;
  events: PresentationRow[];
  mc_confidence: McConfidence;
  presets: string[];
}

export interface WinnerView {
  team_id?: string | null;
  player_id?: string | null;
  undecided?: string;
  tie?: string[];
}

export interface PossessionView {
  by_team: Record<string, number>;
  neutral_s: number;
  sites: number;
  reports: number;
  observed_s: number;
  of_s: number | null;
}

export interface AfterEndPlayer {
  kills: number;
  deaths: number;
}

export interface AfterEndView {
  facts: number;
  by_player: Record<string, AfterEndPlayer>;
}

export interface RecapView {
  winner: WinnerView;
  score: Record<string, number>;
  rows: ScoreRow[];
  honors: Honor[];
  provisional: boolean;
  missing: string[];
  warnings?: string[];
  possession?: PossessionView;
  settling?: boolean;
  awaiting?: string[];
  since_end_ms?: number | null;
  after_end?: AfterEndView;
  post_end_facts?: number;
  post_end?: number;
  parked?: number;
  stations?: RecapStationRow[];
}

export interface MatchHistoryRow {
  match_id: string;
  mode: string;
  go_live_t: number | null;
  ended_t: number | null;
  recap: RecapView | null;
  config?: Record<string, unknown>;
}

export interface VoiceOption {
  id: string;
  name: string;
  family: string;
  speaker?: string;
  lines?: number;
  kill_line: string;
  verified: boolean;
}

export interface VoiceList {
  default: string;
  voices: VoiceOption[];
}

/** The 409 response emitted by NotReadyError; older error bodies may omit these fields. */
export interface PhaseRefusalBody {
  error: string;
  not_ready: string[];
  greens: number;
  roster_size: number;
}

/** A25: one node's log-sync state, as `state.py _set_log()` writes it. Fed ONLY by what the PHONE
 *  reports (`status.log`, `log_offer`, the `log_data` stream) -- MC asking does not make it `offered`.
 *
 *  `state` and `last_t` are written on every call; the other three are carried only when the node said
 *  something about them (`reason` is cleared on every state change, so it never goes stale).
 *  `complete` sticks until something new happens: the phone idles straight back to `none` when it
 *  finishes, and taking that literally would erase the one state the operator is waiting for. */
export interface LogView {
  state: 'none' | 'offered' | 'pulling' | 'held' | 'complete';
  last_t: number;
  /** the node's own words out of `held(2 facts pending)` */
  reason?: string;
  lines?: number;
  bytes?: number;
}

/** One player's row on the readiness board. `state.py readiness()` is the ONLY producer.
 *
 *  NOT `total=False`: `readiness()` builds the row as ONE literal, at the end of the loop body, once
 *  every field it needs (`identity`, `headset`/`headset_proof`, `blockers`/`ambers`, ...) has been
 *  worked out -- so every path through the function writes every key. A reader guarding for a MISSING
 *  key is guarding against nothing, while the fields that really are uncertain arrive as an explicit
 *  `None` and were the ones being read unguarded. What is unknown on this row is the VALUE, never the
 *  key, and `| None` is how that is said. */
export interface ReadinessRow {
  /** "" for a player with no gun assigned */
  gun_id: string;
  /** falls back to the gun_id, then to an em dash */
  sticker: string;
  /** "" when the gun is not in the armory */
  tail: string;
  player_id: string;
  player_num: number;
  /** is a node bound to this player at all */
  present: boolean;
  identity: 'ok' | 'unconfirmed' | 'reverted' | 'unknown' | 'manual';
  node: 'none' | 'linked';
  headset: 'proven' | 'unknown' | 'absent';
  /** A32: HOW the headset was proven, so the UI can say it -- `"echo"` = the gun answered the config
   *  push, `"link"` = a BLE link that has held for HEADSET_LINK_PROOF_MS, `None` = not proven (yet). */
  headset_proof: 'echo' | 'link' | null;
  /** A37: the WEAPON check's own state, and it has THREE answers, not two.
   *  "proven"     -- the gun's slot-0 `$ALCD` carried the magazine the head's `$WEAP,0` wrote;
   *  "mismatch"   -- it carried a different one (the row's red `GUN ECHO ≠ CONFIG` blocker);
   *  "not_echoed" -- the gun answered the head but said nothing about ammo.
   *  The third state exists because it is the NORMAL one in the field: `protocol/brx-protocol.md`
   *  records the `$WEAP` echo as never seen from our v4.32 units and `$ALCD` as streaming on ammo
   *  events only, so the usual answer to a head write is `$START`'s `$LCD,0,0,0,0,0,0,*` and nothing
   *  else. Rendered NEUTRAL (never red, never counted as proven): a green row that ran no weapon
   *  check must be visibly different from one that ran it and passed. `None` = nothing pushed, no
   *  ack yet, the ack is for another head (the stale-ack blocker owns that row), or the head carries
   *  no readable `$WEAP,0` -- in every one of those there is no check to report on. */
  echo: 'proven' | 'mismatch' | 'not_echoed' | null;
  /** Everything below is the NODE's last word, passed through verbatim. `None` = the node has not said
   *  it (or no node is bound): the KEY is always here, the answer may not be. */
  battery_pct: number | null;
  battery_age_ms: number | null;
  /** ms since this node's last packet; None when no node is bound */
  last_seen_age_ms: number | null;
  /** `status.preflight.gun_linked` as last reported */
  gun_linked: boolean | null;
  /** `status.preflight.gun_flapping` (bench 2026-09-17). The card shows one steady HEADSET OFF line while
   *  it is true. An older server omits it, so a reader treats a missing key as false. */
  gun_flapping?: boolean;
  /** F208: `status.pool_stale`; None = not stale or not reported */
  pool_stale: 'silent' | 'no_fire' | 'write_lost' | null;
  /** F208: `status.pool_stale_ms`; None = not reported */
  pool_stale_ms: number | null;
  fw: string | null;
  phone_batt: number | null;
  ssid_ok: boolean | null;
  mc_reachable: boolean | null;
  /** A28.3, stamped by MC from the socket path; None once the socket is gone */
  reach: 'lan' | 'backhaul' | null;
  /** field 2026-09-12 (F155): outlives the socket so a stale row can say which path it had */
  last_reach: 'lan' | 'backhaul' | null;
  synced: boolean | null;
  screen_on: boolean | null;
  foreground: boolean | null;
  /** A29: the phone's real build, as it reported it (`"0.1.9+abc123"`), and its platform. Rendered on
   *  the row so the operator can read WHICH phone is behind without opening the node list. */
  app_ver: string | null;
  platform: string | null;
  /** A25: the same log view the node card carries, on the per-player board. */
  log: LogView | null;
  /** `waiting` = the phone has not connected yet. Blocks the start exactly like `red`, but it is
   *  not a fault and the UI must not paint it as one (field 2026-09-01). */
  status: 'green' | 'amber' | 'red' | 'waiting';
  /** things that actually gate the start */
  blockers: string[];
  /** advisories -- never gate anything */
  ambers: string[];
}

export interface ReadinessSnapshot {
  t: number;
  roster_size: number;
  greens: number;
  board: ReadinessRow[];
  unclaimed: ScanRow[];
  /** Round-2 fix pass B (2026-09-12): faults about the ROSTER AS A WHOLE rather than any one gun —
   *  today exactly one, "all players on one team", which `push_config` and `start` refuse outright
   *  (`force` included). Each entry is operator-facing copy; a non-empty list forces `go` false. */
  roster_faults: string[];
  /** F-3 (2026-09-13): a connected companion phone with a gun set, claimed by nobody on the roster
   *  and not parked on STANDBY either — never blocks `go`, it is the field's own "4 guns connected,
   *  only 2 in lobby" confusion made visible on KIT/LOBBY (`state.py unrostered_phone_count()`). */
  unrostered_phones: number;
  go: boolean;
}

/** LAN details attached to every snapshot. Newer fields stay optional for older MC servers. */
export interface LanView {
  mode: 'router' | 'hotspot' | 'lan' | 'unknown';
  ip: string;
  port: number;
  ws_url: string;
  qr: string;
  ssid?: string | null;
  warning?: string | null;
  join_secret?: string;
  public?: LanPublic;
  auth_required?: boolean;
}

export interface KitView {
  kitted: number;
  total: number;
  trying: Record<string, string>;
  browsing: Record<string, number>;
}

export interface LobbyAck {
  ok: boolean;
  gun_echo?: string;
  err?: string;
  config_id?: string;
}

export interface LobbyView {
  ready: number;
  total: number;
  pushed: boolean;
  acks: Record<string, LobbyAck>;
  all_acked?: boolean;
}

export interface GameAnnouncementView {
  loaded: boolean;
  config_id?: string;
  sent: number;
  total: number;
}

export interface SyncRow {
  player_id: string;
  display: string;
  gun_id: string;
  player_num: number;
  bound: boolean;
  phone_game: boolean;
  gun_sent: boolean;
  gun_acked: boolean;
  gun_echo: 'proven' | 'mismatch' | 'not_echoed' | null;
  ack_state: SyncAckState;
}

export interface SyncTotals {
  rostered: number;
  phone_game: number;
  gun_sent: number;
  gun_acked: number;
  gun_echo_proven: number;
  in_sync: boolean;
}

export interface SyncView {
  rows: SyncRow[];
  totals: SyncTotals;
  unconfigured: string[];
}

export interface SessionOptions {
  log_sync: 'auto' | 'manual';
}

export interface VersionsView {
  field: Record<string, number>;
  newest: string | null;
  release: string | null;
  mc_major: string;
}

export interface NoticesView {
  mc_verify?: string;
}

/** Bench 2026-09-17: bound phones report ARMED/LIVE in a match this MC did not start.
 *
 *  Absent from `State` unless at least one such phone is heard now. `players` are display names.
 *  `can_resume` is false while MC runs or recaps a match of its own (END THEIR MATCH still works). */
export interface OrphanMatchView {
  match_id: string;
  phones: number;
  players: string[];
  arm_state: 'armed' | 'live';
  can_resume: boolean;
}

export interface RestoredFromView {
  at: number | null;
  players: number;
}

export interface SnapshotFeedRow {
  t_match_s: number;
  text: string;
  tag?: string;
  kind: 'kill' | 'sync' | 'info' | 'alert';
}

/** One complete Mission Control snapshot (`GET /api/state` and `/ui-ws`). */
export interface State {
  session_id: string;
  phase: Phase;
  t: number;
  lan: LanView;
  mc_confidence: McConfidence;
  nodes: NodeView[];
  readiness: ReadinessSnapshot;
  config: ConfigView;
  config_errors: string[];
  players: Player[];
  teams: Team[];
  kit: KitView;
  loadout_pool: LoadoutPool;
  lobby: LobbyView;
  feed: SnapshotFeedRow[];
  /** Additive fields below are absent from snapshots emitted by older MC versions. Keep these
   *  optional on the client so rolling a new console back to an older server remains safe. */
  coverage?: Coverage;
  stations?: StationView[];
  game_no?: number;
  config_warnings?: string[];
  standby?: Player[];
  active_preset_id?: string | null;
  restored_from?: RestoredFromView;
  game?: GameAnnouncementView;
  sync?: SyncView;
  options?: SessionOptions;
  versions?: VersionsView;
  start?: StartView | null;
  live?: LiveView | null;
  recap?: RecapView | null;
  notices?: NoticesView;
  end_delivery?: EndDeliveryView;
  /** bench 2026-09-17: absent unless phones are in a match MC did not start */
  orphan_match?: OrphanMatchView;
  /** `--bench-volume N`: every $VOL MC compiles plays at N. Absent on a normal run */
  bench_volume?: number;
  /** S50 build 4: {player_id: resolved effect},
   *  one entry per player carrying a perk (absent players carry none;
   *  the whole key absent when nobody on the roster has a perk). The
   *  SAME numbers `FrameBundle.perk_effects` carries for that player --
   *  `Compiler.perk_effects_resolved()` is the one arithmetic both read,
   *  so the console and the node can never disagree. */
  perk_effects?: Record<string, PerkEffectsResolved>;
}

export interface Envelope {
  v: number;
  kind: string;
  id: string;
  seq?: number;
  t: number;
  body: Record<string, unknown>;
}

/** A47: `POST /api/players/{pid}/operator`. `pushed` means only that a socket took the push: no ack
 *  kind exists for `control`, so the phone's own log and the next heartbeat are the receipt. */
export interface OperatorActionResult {
  ok: boolean;
  cmd: OperatorCmd;
  player_id: string;
  match_id: string;
  pushed: boolean;
}

// ---- required-field tables (mcp/brx_mcp/mc/envelope.py) ----
export declare const REQUIRED: Record<string, readonly string[]>;
export declare const EVENT_REQUIRED: Record<string, readonly string[]>;
export declare const ACCEPT_MIN: Record<string, readonly string[]>;
