// GENERATED by mcp/tools/gen_contract.py from mcp/brx_mcp/mc/types.py + envelope.py -- do not edit; run python3 mcp/tools/gen_contract.py

// ---- constants (types.py §9 + the two envelope.py size caps) ----
/** ---- §9 constants (single source; modules reference by name) ---- */
export const ASSIST_WINDOW_MS = 4000;
export const MULTI_KILL_MS = 4000;
export const FEEDBACK_MAX_AGE_MS = 3000;
export const STATUS_HEARTBEAT_MS = 2000;
export const STALE_AFTER_MS = 8000;
/** A24/M2: how far apart two cap-reaching kills may be and still count as the SAME moment. contracts.md
 *  §7 gives no single number -- it says phone clocks "drift <<1 s over a match" after a lobby re-sync, so
 *  1 s is the width of the band inside which MC cannot tell which of two kills landed first. Two players
 *  reaching the frag cap inside it are reported as a TIE rather than decided by MC's arrival order. */
export const CLOCK_TIE_MS = 1000;
/** F119: the smallest shot count an accuracy number is worth believing. Hits arrive per EVENT and shots
 *  only on the ~2 s status heartbeat, so a row with a handful of shots swings wildly between samples and
 *  can read over 100 %. `honors()` already refused SHARPSHOOTER below this; `ScoreRow.acc_provisional`
 *  now says the same thing about the live number instead of leaving the UI to guess. */
export const ACC_MIN_SHOTS = 10;
/** Past this, a node has not merely gone quiet — it is gone (phone asleep, app closed, gear packed
 *  away). Everything else the board would say about it (gun link lost, clock unsynced, wrong wi-fi,
 *  screen off) is a CONSEQUENCE of that, and listing them as separate faults turns a switched-off
 *  tagger into a wall of red alarms (field 2026-09-02). */
export const OFFLINE_AFTER_MS = 600000;
export const SYNC_FRESH_MS = 10000;
/** A32: how long `status.preflight.gun_linked` must stay TRUE CONTINUOUSLY before the link itself is
 *  accepted as proof that a headset is attached. A gun with NO headset accepts a BLE link and answers a
 *  `$PING`, then drops it within ~6 s (manual/hardware.md, manual/dev.md); switching a linked headset off
 *  makes the gun send `$DISCONNECT,*` and drop the same way. So a link that SURVIVES is the headset --
 *  10 s is the ~6 s drop plus margin for a slow phone and the ~2 s status heartbeat. Shorter and a
 *  headless gun's dying link would read as proven; much longer and the board sits amber for no reason. */
export const HEADSET_LINK_PROOF_MS = 10000;
export const LATE_ARM_GRACE_MS = 8000;
export const CONFIG_TTL_MS = 1800000;
/** wire ids 1..63; 0 reserved (tutorial / unknown shooter) */
export const MAX_PLAYERS = 63;
export const DEATH_LATCH_MS = 2000;
export const RESYNC_PROBE_S = 10;
export const DEFAULT_RUNWAY_S = 120;
export const PROTOCOL_V = 1;
/** advert byte 9 "any team" (`TEAM_ANY` in beacon.js); a control point starts neutral */
export const STATION_TEAM_ANY = 255;
/** net.md §8 size cap */
export const MAX_ENVELOPE_BYTES = 65536;
/** log_data chunk cap (fits under the envelope cap)
 *  ⚠ This is a WHITELIST and an unlisted type is REJECTED at the socket, not ignored downstream --
 *  so a fact the phone learns to send reaches nothing until it is named here (the F40/F60 shape:
 *  both ends report healthy). `possession` is the objective-mode tally (mc/API.md, F70). */
export const MAX_LOG_CHUNK_BYTES = 49152;

// ---- Literal aliases ----
export type ArmState = 'idle' | 'connected' | 'kitted' | 'lobby' | 'armed' | 'live';
export type Phase = 'muster' | 'build' | 'kit' | 'lobby' | 'armed' | 'live' | 'recap';
export type SlotChoice = 'player' | 'host' | 'fixed' | 'off';
export type ItemKind = 'weapon' | 'perk' | 'sidearm';
export type LoadoutPreset = 'open' | 'no_heavies' | 'snipers' | 'custom';
export type StationKind = 'respawn' | 'powerup' | 'extraction' | 'bomb' | 'control';

// ---- kind vocabularies ----
export const MC_KINDS = ['ack', 'alert', 'apply', 'assign', 'config', 'control', 'feedback', 'loadout_ack', 'pull_log', 'result', 'score', 'start', 'station_config', 'time_res', 'tutorial', 'welcome'] as const;
export type McKind = typeof MC_KINDS[number];
export const NODE_KINDS = ['ack_config', 'bind', 'event', 'event_batch', 'hello', 'loadout_browse', 'loadout_request', 'log_data', 'log_offer', 'ready', 'status', 'time_req'] as const;
export type NodeKind = typeof NODE_KINDS[number];
export const CONTROL_CMDS = ['abort_start', 'end', 'panic', 'recall'] as const;
export type ControlCmd = typeof CONTROL_CMDS[number];
export const PERSISTED_EVENT_TYPES = ['death', 'hit_taken', 'possession', 'respawn', 'team_change'] as const;
export type PersistedEventType = typeof PERSISTED_EVENT_TYPES[number];
export const STATION_KINDS = ['respawn', 'powerup', 'extraction', 'bomb', 'control'] as const;
export const STATION_SOURCE_IDS = ['grenade', 'ir_station', 'phone'] as const;
export type StationSourceId = typeof STATION_SOURCE_IDS[number];

// ---- shapes (mcp/brx_mcp/mc/types.py TypedDicts) ----
export interface BleId {
  address?: string;
  uuid?: string;
  tail?: string;
}

export interface ArmoryRecord {
  gun_id: string;
  sticker: string;
  headset_pin: string;
  ble: BleId;
  gen: 'gen2_3' | 'gen1';
  fw: string | null;
  labeled: boolean;
  notes?: string;
}

export interface ScanRow {
  tail: string;
  name: string;
  basename: string;
  gun_id: string | null;
  rssi: number;
  identity: 'ok' | 'unconfirmed' | 'reverted' | 'unknown';
  t: number;
}

export interface WeaponSel {
  weapon_id: string;
}

/** Per-player HP/armour handicap (modes §1.1). Both keys are optional and BOTH may be absent:
 *  `state.py _check_loadout` drops the whole `overrides` key when neither survives validation. */
export interface LoadoutOverrides {
  /** 1..999 (`state.py _check_loadout`); 0 is a corpse, not a pool */
  max_hp?: number;
  /** 0..999 -- 0 is legal and means "one shot with a sniper" */
  max_armor?: number;
}

export interface Loadout {
  /** [primary] or [primary, secondary]; index == gun slot; NEVER empty (A10) */
  weapons: WeaponSel[];
  /** A14: the perk slot — rides beside a secondary weapon (loadout.md §2); an ALT-button perk (easy_reload) is the one that can't */
  perk?: string | null;
  overrides?: LoadoutOverrides;
}

export interface Team {
  team_id: string;
  name: string;
  color: string;
  tid: number;
}

export interface Player {
  player_id: string;
  /** 1..63 on the wire ($PSET token 1); 0 reserved */
  player_num: number;
  display: string;
  team_id: string | null;
  node_id: string | null;
  gun_id: string | null;
  loadout: Loadout;
  voice: string;
  ready: boolean;
  /** A15 (optional): {role: sound id} picks for the $PSET voice fields + the kill line -- WHICH death scream /
   *  pain line / respawn cry of the family the gun plays (voices.PSET_ROLES + "kill"). Absent = the family defaults. */
  voice_slots?: Record<string, string>;
}

export interface RosterEntry {
  player_id: string;
  player_num: number;
  display: string;
  team_id: string | null;
}

export interface Respawn {
  type: 'auto' | 'scanner' | 'none';
  delay_s: number;
}

export interface Scoring {
  frag_limit: number | null;
  win_by: string;
}

export interface Health {
  max_hp: number;
  max_armor: number;
}

/** S14: heal the killer on each kill (Fortnite/CoD "health on kill").
 *
 *  Both are **added** to the killer's own pool and clamped by the gun ($LIFE is additive-clamped),
 *  so they can never overfill. There is deliberately no `shield`: that pool is IR-only (P16), so a
 *  number here would be written and silently do nothing. */
export interface Siphon {
  hp: number;
  armor: number;
}

export interface SlotRule {
  choice: SlotChoice;
  /** primary/secondary: "weapon" | "sidearm" (A12); the perk rule is always ["perk"] (A14) */
  kinds: ItemKind[];
  exclude_tags: string[];
  exclude_ids: string[];
  only_ids: string[];
  fixed_id: string | null;
}

export interface LoadoutPolicy {
  preset: LoadoutPreset;
  hud_select: boolean;
  primary: SlotRule;
  secondary: SlotRule;
  /** A14: perks are their own slot (choice may be "off") */
  perk: SlotRule;
}

export interface LoadoutPool {
  primary: string[];
  secondary_weapons: string[];
  /** A14: the perk slot's pool */
  perks: string[];
}

/** The effect knobs the compiler acts on -- exactly `perks.EFFECT_KEYS`, which `PerkCatalog.__init__`
 *  refuses a perks.json row for exceeding. Every key is optional: a row carries only what it changes. */
export interface PerkEffects {
  /** added to $PSET armour, capped at 255 (`compile.armed_armor`) */
  max_armor_add?: number;
  /** scales the clip/reserve the head writes */
  ammo_mult?: number;
  /** scales the weapon's reload time */
  reload_mult?: number;
  /** A14: claims the ALT button ($BMAP,1,97) -- cannot ride with a second weapon */
  alt_reload?: boolean;
  /** scales $WEAP tok15, the gun's swap delay (bench 2026-09-04) */
  switch_mult?: number;
}

export interface PerkView {
  perk_id: string;
  name: string;
  desc: string;
  tags: string[];
  mechanism: 'passive' | 'slot_frame';
  effects: PerkEffects;
  verified: boolean;
  hidden: boolean;
}

/** One armed utility item on `GameConfig.stations` -- exactly what `state.py _station_ids()` builds
 *  (`{"id": a["id"], "kind": a["kind"]}`), sorted by id. Both keys are always present. */
export interface StationRef {
  id: number;
  kind: StationKind;
}

export interface Stun {
  /** F15/A20: seconds a hit EMP keeps the gun disarmed (default 10, 1..60) */
  duration_s?: number;
}

export interface GameConfig {
  config_id: string;
  mode: string;
  environment: 'indoor' | 'outdoor';
  night: boolean;
  /** required (>0) on the phone path; None only for full-coverage venues */
  time_limit_s: number | null;
  respawn: Respawn;
  scoring: Scoring;
  health: Health;
  teams: Team[];
  led?: Record<string, unknown>;
  /** A6.5 */
  player_num_base?: number;
  /** S14: heal-on-kill; absent or {0,0} = off */
  siphon?: Siphon;
  /** A13.1 (F104): the utility items MC armed for THIS game, when at least one is assigned.
   *  Set by `Session._wire_config()` from the ITEMS assignments, never by the
   *  operator; a player phone honours only these ids (`engine.js _stationAllowed`) --
   *  and when the list is ABSENT (nothing assigned) it honours ANY station (the hand-armed fallback). */
  stations?: StationRef[];
  /** F70: what is emitting this game's objective -- `STATION_SOURCES` above
   *  ("grenade" = a BRX Smart Grenade in hill mode, "ir_station" = a
   *  $CAPTURE-speaking station). Present only for the modes that need one
   *  (domination/koth/ctf/cs/bomb); `validate()` refuses those without it. */
  station_source?: string;
  /** A10 (loadout.md §3); filled with the mode default when absent */
  loadout_policy?: LoadoutPolicy;
  /** A11 (mc/presentation.py): sounds + lights per event, preset or custom */
  presentation?: Record<string, unknown>;
  /** A17: per-WEAPON $SIR sounds. DEFAULT OFF -- bench F38: a non-empty
   *  $SIR sound REPLACES the $PSET pool sound rather than layering, so
   *  turning this on SILENCES the ear-confirmed material layer (armour
   *  metal / shield fizz / silent health) on every standard hit. */
  hit_audio_class?: boolean;
  /** A17: give each weapon FAMILY its own $SIR cell so hits sound different
   *  per weapon. DEFAULT OFF -- an unmatched cell is silently ignored (the
   *  F11 shape), so it stays off until FOLLOWUPS F38/F39 clear it at the bench. */
  hit_audio_rekey?: boolean;
  /** F15/A20: the host-driven STUN (EMP). Present = the `<8,0>` $SIR cell
   *  ships as fn 24 (status, no damage) and a proto-8 $HIR disarms the
   *  victim's node for `duration_s` (default 10, 1..60). Absent = the stock
   *  charge-rifle damage row, byte-for-byte. Source: a $WEAP t3=8 slot
   *  (the charge rifle) or a proto-8 station. */
  stun?: Stun;
  /** A31/A4.8: the VENUE's radio coverage -- "full" = every phone is on
   *  the LAN for the whole match (the only case where `time_limit_s` may
   *  be null and where an MC-decided end needs no "verify at MC" warning).
   *  Absent/anything else = partial. `compile.full_coverage()` is the one
   *  reader; `opts.coverage` (the CLI/sim path) still wins. */
  coverage?: 'full' | 'partial';
  /** A18 (E1): the MODE's own rules -- what its engine declares in `PARAMS`
   *  (`modes/params.py`; schema per mode from `GET /api/modes`). Present, and
   *  COMPLETE (defaults filled), for every mode whose engine declares any;
   *  absent for one that declares none (tdm/ffa/infection), so those configs
   *  are byte-identical to before the field existed. Unknown keys and
   *  out-of-range values are refused at PUT and again by `validate()`.
   *  Rides the wire as-is: a node reads its rules from here, never from a
   *  schema of its own. */
  mode_params?: Record<string, number | boolean | string>;
  /** A19 (S10): who the VIP is. Must name a rostered player (`validate()`);
   *  MC pushes them the `vip` headset role (`alert.role`) once the match is
   *  live and again after each of their respawns. Never stored in a saved
   *  game (a preset names no person). */
  vip_player_id?: string | null;
}

export interface FrameBundle {
  config_id: string;
  player_id: string;
  /** config head, NO $SPAWN, no countdown sound; ends with $TID */
  head: string[];
  /** $PLAYX,0 -> $SPAWN,, -> $AMMO... -> $BMAP,0,0 */
  spawn: string[];
  revive: string[];
  end: string[];
  panic: string[];
  team_flip?: Record<string, string[]>;
  /** F86: per-tid [blank, rest] the node takes the gun with after a flip */
  team_flip_take?: Record<string, string[]>;
  /** A6.3: key -> PRE-COMPOSED frame the node writes verbatim. countdown, kill,
   *  game_over?, victory?, tick?, klaxon?, multi?, medal?, runway_*?, and the once-per-life
   *  low-health pair hurt?/hurt_led? (hurt_led is an $HLED, not a $PLAY — see compile.cues)
   *  A11: plus one key per presentation EVENT that carries a sound (hit_taken … vip_down); "" = deliberately mute.
   *  A15.2: `spawn` = the character's spawn line, written by the node IMMEDIATELY after the spawn / revive frames
   *  (the head's $PSET ships an empty battleRespawnCry, so the firmware itself says nothing on $SPAWN).
   *  A15.3: `pain_short` / `pain_long` / `pain_melee` = the pain the node plays on a $HIR (the $PSET pain fields ship
   *  empty): a melee word -> pain_melee; damage >= voice.pain_long_min -> pain_long; else pain_short. At most one per
   *  600 ms, none on the lethal hit (the firmware's death scream covers it). */
  cues: Record<string, string>;
  /** A11: event -> [[frame, hold_s], ...] -- the tuned $GLED burst (+ optional $HLED) */
  leds?: Record<string, unknown[]>;
  /** A11: presentation.summary() -- preset + switches, for the UI/HUD */
  presentation?: Record<string, unknown>;
  /** A11.7: {in_play team|dark|health, blank, rest, bands?[[frac,f]]} -- absent for native */
  gun?: Record<string, unknown>;
  /** A11.6: {in_play, rest, blank, pregame[], start[[f,s]], hit[[f,s]], death[[f,s]], respawn[[f,s]], carrier{tid:[[f,s]]}} */
  headset?: Record<string, unknown>;
  /** 2026-09-04: the weapon-swap delay the gun enforces (max tok15 of slots 0/1, after perks) */
  swap_ms?: number;
  /** A15.1: event -> frames; the node picks ONE at random per event; `cues[ev]` is the deterministic first */
  cue_pools?: Record<string, string[]>;
  /** A15: {id, family, pset{role: id}, kill, rolled{role: id} (A15.1: this push's draws), pools{role: [ids]},
   *  spawn: [ids] (A15.2: the spawn pool; `pset.respawn_cry` is "" unless picked),
   *  pset_pool: [death-scream ids, one per `pset_pool` frame], pain_long_min: int} (A15.3) */
  voice?: Record<string, unknown>;
  /** A15.3: the node writes ONE of these at random immediately before every `$SPAWN` (spawn and revive),
   *  so the firmware's death scream changes per life. One full $PSET per death-scream take; only the
   *  deathScream token differs. A pinned `death_scream` (or a one-take family) = one frame = head[4].
   *  A17: each take ALSO carries its own hitHp/hitArrmor/hitShield/hitCrit draw (hitaudio.MATERIAL_POOLS). */
  pset_pool?: string[];
  /** A17: one full `$SIR` table per take -- the node writes one before every `$SPAWN` and again after a
   *  lull, so the same weapon does not land the same clip all match. Re-sending `$SIR` rows is the F11 repair
   *  path, so the write is safe by construction; the rows are identical apart from their sound tokens. */
  sir_pool?: string[][];
  /** A17: {rekey: bool, cells{weapon_id: "p,s"}, classes{"p,s": family}, shared[families sharing a cell],
   *  material[roles]} -- what the UI/console shows for "what does a hit sound like", and what a bench probe reads. */
  hit_audio?: Record<string, unknown>;
}

export interface Weapon {
  weapon_id: string;
  name: string;
  cls: string;
  /** house-written armory blurb (weapons.json `desc`); "" if a row lacks one */
  desc?: string;
  stats: Record<string, unknown>;
  weap_frame: string;
  icon?: string;
  verified?: boolean;
  /** A10 policy vocabulary (loadout.md §1.1) */
  tags?: string[];
  role?: string;
  /** A10: human copy for a known LIVE problem (weapons.json `caution`) */
  caution?: string;
}

export interface Preflight {
  ssid_ok?: boolean;
  mc_reachable?: boolean;
  auto_join_ok?: boolean;
  cellular_off?: boolean;
  dnd_on?: boolean;
  phone_batt?: number;
  screen_on?: boolean;
  foreground?: boolean;
  gun_linked?: boolean;
  headset_ok?: boolean;
}

export interface Event {
  type?: 'hit_taken' | 'death' | 'respawn' | 'team_change' | 'status' | 'possession';
  t?: number;
  match_id?: string | null;
  node_id?: string;
  player_id?: string | null;
  /** hit_taken / death */
  shooter_num?: number;
  shooter_team?: number;
  dmg?: number;
  ir_proto?: number;
  /** $HIR tok1 — WHICH sensor caught the shot. 0-3 are ALL HEADSET sensors (the headset carries
   *  FOUR, operator-confirmed 2026-09-01; only 0 = front and 1 = back are bench-mapped), 4 = gun
   *  body. Forwarded 2026-09-01: it was parsed on the phone and dropped, so a
   *  "the headset domes never register" report could only be checked against a frame ring. */
  sensor?: number;
  desync?: boolean;
  /** respawn */
  resync?: boolean;
  /** team_change */
  tid?: number;
  /** possession (F70, objective modes) — a CUMULATIVE tally for ONE control point, resent as it grows.
   *  `hold_ms` maps a TEAM TID (as a string key on the wire: JSON has no integer keys) to the ms this
   *  node observed that team OWNING the point; tid 2 on a hill is NEUTRAL, not a team. `observed_ms` is
   *  how long it could hear the point at all, which is what makes the number a stated lower bound
   *  rather than a claim. `site` is "A" for the single grenade point (F88: a beacon carries no id).
   *  MC merges these by MAX per (site, team) and NEVER by sum — see `scoring._possession`. */
  site?: string;
  hold_ms?: Record<string, number>;
  observed_ms?: number;
  source?: 'beacon' | 'station';
  /** status */
  hp?: number;
  armor?: number;
  ammo?: number;
  alive?: boolean;
  shots?: number;
  deadline_s?: number;
  battery?: number;
  fw?: string;
  arm_state?: ArmState;
  t_minus_ms?: number;
  synced?: boolean;
  dropped?: number;
  preflight?: Preflight;
}

export interface ScoreRow {
  player_id: string;
  display: string;
  team_id: string | null;
  kills: number;
  deaths: number;
  assists: number;
  shots: number;
  hits: number;
  accuracy: number | null;
  kd: number;
  /** CURRENT streak — 0 for whoever died last. `best_streak` is the one to show. */
  streak: number;
  medals: string[];
  /** --- additive, 2026-09-11 (F116 / F119). NotRequired, not merely new: `scoring.py` fills all five on
   *  every LIVE row, but a session PERSISTED before the change replays rows without them, so a reader that
   *  assumes them crashes on last week's recap. Never read one without a fallback. ---
   *  shots incl. the pre-hot-swap baseline (A6.2); == `shots` */
  shots_total?: number;
  /** F116: the LONGEST streak this match. `streak` stayed for compatibility. */
  best_streak?: number;
  /** the biggest multi-kill (2 = double, 3 = triple, 4+ = killtacular); 0 = none */
  multi_best?: number;
  /** this player drew first blood */
  first_blood?: boolean;
  /** F119: `accuracy` is not settled yet — render it as settling, not as fact */
  acc_provisional?: boolean;
}

/** A25: one node's log-sync state, as `state.py _set_log()` writes it. Fed ONLY by what the PHONE
 *  reports (`status.log`, `log_offer`, the `log_data` stream) -- MC asking does not make it `offered`.
 *
 *  `state` and `last_t` are written on every call; the other three are carried only when the node said
 *  something about them (`reason` is cleared on every state change, so it never goes stale).
 *  `complete` sticks until something new happens: the phone idles straight back to `none` when it
 *  finishes, and taking that literally would erase the one state the operator is waiting for. */
export interface LogView {
  state: 'none' | 'offered' | 'pulling' | 'held' | 'complete';
  last_t: number;
  /** the node's own words out of `held(2 facts pending)` */
  reason?: string;
  lines?: number;
  bytes?: number;
}

/** One player's row on the readiness board. `state.py readiness()` is the ONLY producer.
 *
 *  NOT `total=False`: every path through `readiness()` writes every key here -- the opening literal, all
 *  three arms of the headset branch, and the closing `row.update`. So a reader guarding for a MISSING key
 *  is guarding against nothing, while the fields that really are uncertain arrive as an explicit `None`
 *  and were the ones being read unguarded. What is unknown on this row is the VALUE, never the key, and
 *  `| None` is how that is said. */
export interface ReadinessRow {
  /** "" for a player with no gun assigned */
  gun_id: string;
  /** falls back to the gun_id, then to an em dash */
  sticker: string;
  /** "" when the gun is not in the armory */
  tail: string;
  player_id: string;
  player_num: number;
  /** is a node bound to this player at all */
  present: boolean;
  identity: 'ok' | 'unconfirmed' | 'reverted' | 'unknown' | 'manual';
  node: 'none' | 'linked';
  headset: 'proven' | 'unknown' | 'absent';
  /** A32: HOW the headset was proven, so the UI can say it -- `"echo"` = the gun answered the config
   *  push, `"link"` = a BLE link that has held for HEADSET_LINK_PROOF_MS, `None` = not proven (yet). */
  headset_proof: 'echo' | 'link' | null;
  /** Everything below is the NODE's last word, passed through verbatim. `None` = the node has not said
   *  it (or no node is bound): the KEY is always here, the answer may not be. */
  battery_pct: number | null;
  battery_age_ms: number | null;
  /** ms since this node's last packet; None when no node is bound */
  last_seen_age_ms: number | null;
  /** `status.preflight.gun_linked` as last reported */
  gun_linked: boolean | null;
  fw: string | null;
  phone_batt: number | null;
  ssid_ok: boolean | null;
  mc_reachable: boolean | null;
  synced: boolean | null;
  screen_on: boolean | null;
  foreground: boolean | null;
  /** A29: the phone's real build, as it reported it (`"0.1.9+abc123"`), and its platform. Rendered on
   *  the row so the operator can read WHICH phone is behind without opening the node list. */
  app_ver: string | null;
  platform: string | null;
  /** A25: the same log view the node card carries, on the per-player board. */
  log: LogView | null;
  /** `waiting` = the phone has not connected yet. Blocks the start exactly like `red`, but it is
   *  not a fault and the UI must not paint it as one (field 2026-09-01). */
  status: 'green' | 'amber' | 'red' | 'waiting';
  /** things that actually gate the start */
  blockers: string[];
  /** advisories -- never gate anything */
  ambers: string[];
}

export interface ReadinessSnapshot {
  t: number;
  roster_size: number;
  greens: number;
  board: ReadinessRow[];
  unclaimed: ScanRow[];
  go: boolean;
}

export interface Envelope {
  v: number;
  kind: string;
  id: string;
  seq?: number;
  t: number;
  body: Record<string, unknown>;
}

// ---- required-field tables (mcp/brx_mcp/mc/envelope.py) ----
export const REQUIRED: Record<string, readonly string[]> = {
  hello: ['node_id', 'node_type', 'app_ver', 'seq_next'],
  bind: ['node_id', 'gun_name', 'gun_tail'],
  event: [],
  event_batch: ['events'],
  status: ['node_id', 'arm_state', 'synced'],
  ack_config: ['config_id', 'ok'],
  time_req: ['t_node'],
  log_offer: ['node_id', 'bytes', 'lines'],
  log_data: ['node_id', 'seq', 'chunk', 'last'],
  ready: ['node_id', 'player_id', 'ready'],
  loadout_request: ['node_id', 'player_id', 'slot', 'kind'],
  loadout_browse: ['node_id', 'player_id', 'open'],
  welcome: ['session_id', 'server_t', 'seq_hi'],
  assign: ['player', 'team', 'roster'],
  tutorial: ['frames'],
  config: ['config', 'frames', 'roster'],
  start: ['match_id', 'go_live_t', 'config_id', 'seq', 'countdown_s'],
  feedback: ['player_id', 'kind', 't'],
  control: ['cmd'],
  time_res: ['t_node', 'server_t'],
  pull_log: [],
  ack: ['seq_hi'],
  apply: ['frames'],
  loadout_ack: ['slot', 'ok'],
  score: ['player_id'],
  alert: ['kind', 'text', 'player_id', 't'],
  result: ['match_id', 'outcome', 'winner', 'rows', 'provisional', 't'],
  station_config: ['kind', 'team', 'id'],
};
export const EVENT_REQUIRED: Record<string, readonly string[]> = {
  hit_taken: ['shooter_num', 'shooter_team', 'dmg'],
  death: ['shooter_num', 'shooter_team'],
  respawn: [],
  team_change: ['tid'],
  possession: ['hold_ms'],
};
export const ACCEPT_MIN: Record<string, readonly string[]> = {
  result: ['match_id'],
};
