export {
  POWERUP_CHARGES_MIN as CHARGES_MIN,
  POWERUP_CHARGES_MAX as CHARGES_MAX,
  POWERUP_AMOUNT_MIN as AMOUNT_MIN,
  POWERUP_AMOUNT_MAX as AMOUNT_MAX,
  POWERUP_AMOUNT_STEP as AMOUNT_STEP,
  POWERUP_SPAWN_EVERY_MIN as SPAWN_EVERY_MIN,
  POWERUP_SPAWN_EVERY_MAX as SPAWN_EVERY_MAX,
  POWERUP_SPAWN_EVERY_STEP as SPAWN_EVERY_STEP,
} from '../api/contract.gen';
