// The phone-side half of the contract-DRY adoption (contract-dry-spec.md §4): envelope.js's
// constants/tables now come from the GENERATED app/src/transport/contract.gen.js, and the
// hand-written KIND maps (beacon.js, utility.js) that used to mirror STATION_KINDS by comment only
// are pinned against the generated set here instead.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as CONTRACT from '../src/transport/contract.gen.js';
import * as E from '../src/transport/envelope.js';
import { KIND } from '../src/beacon.js';

// utility.js's KIND_LABEL is module-private; read the source rather than eval the whole (DOM-touching)
// module. Same approach envelope.js's generated-file tests use elsewhere in this repo (test_contract_kinds.py).
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const HERE = path.dirname(fileURLToPath(import.meta.url));
const UTILITY_SRC = readFileSync(path.resolve(HERE, '../src/utility.js'), 'utf8');

function kindLabelKeys() {
  const m = UTILITY_SRC.match(/const KIND_LABEL = \{([^}]*)\}/);
  assert.ok(m, 'KIND_LABEL not found in utility.js');
  return new Set([...m[1].matchAll(/(\w+):/g)].map(x => x[1]));
}

test('beacon.js KIND keys equal the generated STATION_KINDS set', () => {
  assert.deepEqual(new Set(Object.keys(KIND)), CONTRACT.STATION_KINDS);
});

test('utility.js KIND_LABEL keys equal the generated STATION_KINDS set', () => {
  assert.deepEqual(kindLabelKeys(), CONTRACT.STATION_KINDS);
});

test('a result with only match_id decodes on the phone (direction "mc", A24/ACCEPT_MIN)', () => {
  const env = E.makeEnvelope('result', { match_id: 'm1' });
  const got = E.decode(E.encode(env), 'mc');
  assert.deepEqual(got.body, { match_id: 'm1' });
});

test('the same short result body is refused MC->node strictness where the kind is checked at all', () => {
  // 'result' is MC->node only (not in NODE_KINDS), so direction 'node' rejects it at the kind
  // allowlist before ever reaching a field check — proving the node never emits it. Separately,
  // REQUIRED.result (the sender's full promise) demands strictly more than ACCEPT_MIN accepts.
  const env = E.makeEnvelope('result', { match_id: 'm1' });
  assert.throws(() => E.decode(E.encode(env), 'node'), /unknown_kind/);
  assert.ok(CONTRACT.REQUIRED.result.length > CONTRACT.ACCEPT_MIN.result.length);
});

test('possession is in PERSISTED_EVENT_TYPES', () => {
  assert.ok(E.PERSISTED_EVENT_TYPES.has('possession'));
  assert.ok(CONTRACT.PERSISTED_EVENT_TYPES.has('possession'));
});

test('envelope.js re-exports every name contract.gen.js exports that envelope.js exported before', () => {
  // The names envelope.js exported before this file split (contract-dry-spec.md §4) that are now
  // sourced from contract.gen.js. Function exports (EnvelopeError, uid, makeEnvelope, encode,
  // byteLength, validateEvent, validate, decode) are hand-written in envelope.js, not generated,
  // so they are deliberately excluded from this list.
  const namesExportedBefore = [
    'PROTOCOL_V', 'STATUS_HEARTBEAT_MS', 'STALE_AFTER_MS', 'SYNC_FRESH_MS', 'FEEDBACK_MAX_AGE_MS',
    'LATE_ARM_GRACE_MS', 'DEATH_LATCH_MS', 'RESYNC_PROBE_S', 'MAX_PLAYERS', 'MAX_ENVELOPE_BYTES',
    'MAX_LOG_CHUNK_BYTES', 'PERSISTED_EVENT_TYPES', 'NODE_KINDS', 'MC_KINDS', 'CONTROL_CMDS',
  ];
  for (const name of namesExportedBefore) {
    assert.ok(name in CONTRACT, `${name} is no longer generated by contract.gen.js`);
    assert.ok(name in E, `envelope.js dropped the ${name} re-export`);
    assert.equal(E[name], CONTRACT[name], `envelope.js.${name} no longer matches contract.gen.js.${name}`);
  }
});
